import type { DomainEventEmitInput } from './types';

/** Stable domain event type strings — use these instead of literals at emit sites. */
export const DOMAIN_EVENT_TYPES = {
  USER_PREFERENCE_UPDATED: 'user.preference.updated',
  MODULE_INSTALLED: 'module.installed',
  MODULE_UNINSTALLED: 'module.uninstalled',
  MODULE_ENABLED: 'module.enabled',
  MODULE_DISABLED: 'module.disabled',
  BUSINESS_MEMBER_ADDED: 'business.member.added',
  BUSINESS_MEMBER_REMOVED: 'business.member.removed',
  BUSINESS_UPDATED: 'business.updated',
  FILE_UPLOADED: 'file.uploaded',
  FILE_DELETED: 'file.deleted',
  FILE_SHARED: 'file.shared',
  FILE_RENAMED: 'file.renamed',
  FILE_MOVED: 'file.moved',
  FILE_RESTORED: 'file.restored',
  FILE_UNSHARED: 'file.unshared',
  FOLDER_SHARED: 'folder.shared',
  FOLDER_CREATED: 'folder.created',
  FOLDER_RENAMED: 'folder.renamed',
  FOLDER_MOVED: 'folder.moved',
  FOLDER_DELETED: 'folder.deleted',
  FOLDER_RESTORED: 'folder.restored',
  FOLDER_UNSHARED: 'folder.unshared',
  CHAT_CONVERSATION_CREATED: 'chat.conversation.created',
  CHAT_CONVERSATION_TRASHED: 'chat.conversation.trashed',
  CHAT_CONVERSATION_RESTORED: 'chat.conversation.restored',
  CHAT_CONVERSATION_PERMANENTLY_DELETED: 'chat.conversation.permanentlyDeleted',
  CHAT_MESSAGE_SENT: 'chat.message.sent',
  CHAT_MESSAGE_DELETED: 'chat.message.deleted',
  CHAT_MESSAGE_RESTORED: 'chat.message.restored',
  CHAT_MESSAGE_PERMANENTLY_DELETED: 'chat.message.permanentlyDeleted',
  CHAT_MESSAGE_REACTION_ADDED: 'chat.message.reactionAdded',
  CHAT_MESSAGE_READ: 'chat.message.read',
  CALENDAR_CREATED: 'calendar.calendar.created',
  CALENDAR_UPDATED: 'calendar.calendar.updated',
  CALENDAR_DELETED: 'calendar.calendar.deleted',
  CALENDAR_EVENT_CREATED: 'calendar.event.created',
  CALENDAR_EVENT_UPDATED: 'calendar.event.updated',
  CALENDAR_EVENT_DELETED: 'calendar.event.deleted',
  CALENDAR_EVENT_TRASHED: 'calendar.event.trashed',
  CALENDAR_EVENT_RESTORED: 'calendar.event.restored',
  CALENDAR_EVENT_PERMANENTLY_DELETED: 'calendar.event.permanentlyDeleted',
  CALENDAR_EVENT_RSVP_UPDATED: 'calendar.event.rsvpUpdated',
  CALENDAR_EVENT_REMINDER_DISPATCHED: 'calendar.event.reminderDispatched',
  TODO_TASK_CREATED: 'todo.task.created',
  TODO_TASK_UPDATED: 'todo.task.updated',
  TODO_TASK_COMPLETED: 'todo.task.completed',
  TODO_TASK_REOPENED: 'todo.task.reopened',
  TODO_TASK_ASSIGNED: 'todo.task.assigned',
  TODO_TASK_UNASSIGNED: 'todo.task.unassigned',
  TODO_TASK_TRASHED: 'todo.task.trashed',
  TODO_TASK_RESTORED: 'todo.task.restored',
  TODO_TASK_PERMANENTLY_DELETED: 'todo.task.permanentlyDeleted',
  VLINK_CREATED: 'vlink.created',
  VLINK_UPDATED: 'vlink.updated',
  VLINK_ARCHIVED: 'vlink.archived',
  VLINK_DELETED: 'vlink.deleted',
  VLINK_RESTORED: 'vlink.restored',
  VLINK_MEMBER_ADDED: 'vlink.member.added',
  VLINK_MEMBER_UPDATED: 'vlink.member.updated',
  VLINK_MEMBER_REMOVED: 'vlink.member.removed',
  VLINK_OWNERSHIP_TRANSFERRED: 'vlink.ownership.transferred',
  VLINK_ENTITY_LINKED: 'vlink.entity.linked',
  VLINK_ENTITY_UNLINKED: 'vlink.entity.unlinked',
  VLINK_SUGGESTION_CREATED: 'vlink.suggestion.created',
  VLINK_SUGGESTION_ACCEPTED: 'vlink.suggestion.accepted',
  VLINK_SUGGESTION_REJECTED: 'vlink.suggestion.rejected',
} as const;

export type DomainEventType = (typeof DOMAIN_EVENT_TYPES)[keyof typeof DOMAIN_EVENT_TYPES];

export interface DomainEventContract {
  type: DomainEventType;
  entityType: string;
  defaultAction: string;
  version: number;
  description: string;
  recommendedMetadataFields: readonly string[];
  disallowedMetadataFields: readonly string[];
}

const GLOBAL_DISALLOWED_METADATA = [
  'password',
  'token',
  'secret',
  'accessToken',
  'refreshToken',
  'value',
  'rawValue',
  'configuration',
  'configured',
  'fileContent',
  'content',
  'body',
  'email',
] as const;

export const DOMAIN_EVENT_CONTRACTS: Record<DomainEventType, DomainEventContract> = {
  [DOMAIN_EVENT_TYPES.USER_PREFERENCE_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.USER_PREFERENCE_UPDATED,
    entityType: 'UserPreference',
    defaultAction: 'update',
    version: 1,
    description: 'User updated a preference key (value not included in metadata).',
    recommendedMetadataFields: ['key'],
    disallowedMetadataFields: ['value', 'rawValue'],
  },
  [DOMAIN_EVENT_TYPES.MODULE_INSTALLED]: {
    type: DOMAIN_EVENT_TYPES.MODULE_INSTALLED,
    entityType: 'ModuleInstallation',
    defaultAction: 'install',
    version: 1,
    description: 'Module installed for personal or business scope.',
    recommendedMetadataFields: ['moduleId', 'installScope', 'businessId', 'installationId'],
    disallowedMetadataFields: ['configured', 'configuration'],
  },
  [DOMAIN_EVENT_TYPES.MODULE_UNINSTALLED]: {
    type: DOMAIN_EVENT_TYPES.MODULE_UNINSTALLED,
    entityType: 'ModuleInstallation',
    defaultAction: 'uninstall',
    version: 1,
    description: 'Module uninstalled from personal or business scope.',
    recommendedMetadataFields: ['moduleId', 'installScope', 'businessId'],
    disallowedMetadataFields: ['configured', 'configuration'],
  },
  [DOMAIN_EVENT_TYPES.MODULE_ENABLED]: {
    type: DOMAIN_EVENT_TYPES.MODULE_ENABLED,
    entityType: 'ModuleInstallation',
    defaultAction: 'enable',
    version: 1,
    description: 'Module installation enabled.',
    recommendedMetadataFields: ['moduleId', 'installScope', 'businessId', 'installationId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.MODULE_DISABLED]: {
    type: DOMAIN_EVENT_TYPES.MODULE_DISABLED,
    entityType: 'ModuleInstallation',
    defaultAction: 'disable',
    version: 1,
    description: 'Module installation disabled.',
    recommendedMetadataFields: ['moduleId', 'installScope', 'businessId', 'installationId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.BUSINESS_MEMBER_ADDED]: {
    type: DOMAIN_EVENT_TYPES.BUSINESS_MEMBER_ADDED,
    entityType: 'BusinessMember',
    defaultAction: 'add',
    version: 1,
    description: 'User became an active business member.',
    recommendedMetadataFields: ['memberUserId', 'role'],
    disallowedMetadataFields: ['email', 'token'],
  },
  [DOMAIN_EVENT_TYPES.BUSINESS_MEMBER_REMOVED]: {
    type: DOMAIN_EVENT_TYPES.BUSINESS_MEMBER_REMOVED,
    entityType: 'BusinessMember',
    defaultAction: 'remove',
    version: 1,
    description: 'User removed from business (adopted on remove member paths).',
    recommendedMetadataFields: ['memberUserId', 'role'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.BUSINESS_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.BUSINESS_UPDATED,
    entityType: 'Business',
    defaultAction: 'update',
    version: 1,
    description: 'Business profile or branding updated.',
    recommendedMetadataFields: ['changedFields', 'updateKind'],
    disallowedMetadataFields: [
      'ein',
      'logo',
      'logoUrl',
      'settings',
      'manifest',
      'configuration',
      'configured',
      'website',
      'description',
    ],
  },
  [DOMAIN_EVENT_TYPES.FILE_UPLOADED]: {
    type: DOMAIN_EVENT_TYPES.FILE_UPLOADED,
    entityType: 'File',
    defaultAction: 'upload',
    version: 1,
    description: 'File uploaded to Drive.',
    recommendedMetadataFields: ['folderId', 'fileType', 'sizeBytes', 'dashboardId'],
    disallowedMetadataFields: ['content', 'fileContent', 'url', 'path', 'signedUrl'],
  },
  [DOMAIN_EVENT_TYPES.FILE_DELETED]: {
    type: DOMAIN_EVENT_TYPES.FILE_DELETED,
    entityType: 'File',
    defaultAction: 'delete',
    version: 1,
    description: 'File moved to trash or removed from Drive.',
    recommendedMetadataFields: ['folderId', 'softDelete', 'dashboardId'],
    disallowedMetadataFields: ['content', 'url', 'path', 'signedUrl'],
  },
  [DOMAIN_EVENT_TYPES.FILE_SHARED]: {
    type: DOMAIN_EVENT_TYPES.FILE_SHARED,
    entityType: 'File',
    defaultAction: 'share',
    version: 1,
    description: 'File permission granted to another user.',
    recommendedMetadataFields: ['recipientUserId', 'canRead', 'canWrite', 'shareRole'],
    disallowedMetadataFields: ['url', 'path', 'signedUrl', 'email'],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_SHARED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_SHARED,
    entityType: 'Folder',
    defaultAction: 'share',
    version: 1,
    description: 'Folder permission granted to another user.',
    recommendedMetadataFields: ['recipientUserId', 'canRead', 'canWrite', 'shareRole'],
    disallowedMetadataFields: ['url', 'path', 'signedUrl', 'email'],
  },
  [DOMAIN_EVENT_TYPES.FILE_RENAMED]: {
    type: DOMAIN_EVENT_TYPES.FILE_RENAMED,
    entityType: 'File',
    defaultAction: 'rename',
    version: 1,
    description: 'File renamed in File Hub.',
    recommendedMetadataFields: ['fileName', 'previousName', 'folderId', 'dashboardId'],
    disallowedMetadataFields: ['content', 'url', 'path'],
  },
  [DOMAIN_EVENT_TYPES.FILE_MOVED]: {
    type: DOMAIN_EVENT_TYPES.FILE_MOVED,
    entityType: 'File',
    defaultAction: 'move',
    version: 1,
    description: 'File moved to another folder.',
    recommendedMetadataFields: ['folderId', 'previousFolderId', 'dashboardId', 'fileName'],
    disallowedMetadataFields: ['content', 'url', 'path'],
  },
  [DOMAIN_EVENT_TYPES.FILE_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.FILE_RESTORED,
    entityType: 'File',
    defaultAction: 'restore',
    version: 1,
    description: 'File restored from trash.',
    recommendedMetadataFields: ['folderId', 'dashboardId', 'fileName'],
    disallowedMetadataFields: ['content', 'url', 'path'],
  },
  [DOMAIN_EVENT_TYPES.FILE_UNSHARED]: {
    type: DOMAIN_EVENT_TYPES.FILE_UNSHARED,
    entityType: 'File',
    defaultAction: 'unshare',
    version: 1,
    description: 'File share permission revoked.',
    recommendedMetadataFields: ['recipientUserId', 'fileName', 'dashboardId'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_CREATED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_CREATED,
    entityType: 'Folder',
    defaultAction: 'create',
    version: 1,
    description: 'Folder created in File Hub.',
    recommendedMetadataFields: ['parentId', 'dashboardId', 'folderName'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_RENAMED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_RENAMED,
    entityType: 'Folder',
    defaultAction: 'rename',
    version: 1,
    description: 'Folder renamed in File Hub.',
    recommendedMetadataFields: ['folderName', 'previousName', 'parentId', 'dashboardId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_MOVED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_MOVED,
    entityType: 'Folder',
    defaultAction: 'move',
    version: 1,
    description: 'Folder moved to another parent.',
    recommendedMetadataFields: ['parentId', 'previousParentId', 'dashboardId', 'folderName'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_DELETED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_DELETED,
    entityType: 'Folder',
    defaultAction: 'delete',
    version: 1,
    description: 'Folder moved to trash or permanently deleted.',
    recommendedMetadataFields: ['parentId', 'softDelete', 'dashboardId', 'folderName'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_RESTORED,
    entityType: 'Folder',
    defaultAction: 'restore',
    version: 1,
    description: 'Folder restored from trash.',
    recommendedMetadataFields: ['parentId', 'dashboardId', 'folderName'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_UNSHARED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_UNSHARED,
    entityType: 'Folder',
    defaultAction: 'unshare',
    version: 1,
    description: 'Folder share permission revoked.',
    recommendedMetadataFields: ['recipientUserId', 'folderName', 'dashboardId'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_CREATED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_CREATED,
    entityType: 'Conversation',
    defaultAction: 'create',
    version: 1,
    description: 'Chat conversation created.',
    recommendedMetadataFields: ['moduleId', 'conversationType', 'dashboardId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_TRASHED,
    entityType: 'Conversation',
    defaultAction: 'trash',
    version: 1,
    description: 'Chat conversation moved to trash.',
    recommendedMetadataFields: ['moduleId', 'dashboardId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_RESTORED,
    entityType: 'Conversation',
    defaultAction: 'restore',
    version: 1,
    description: 'Chat conversation restored from trash.',
    recommendedMetadataFields: ['moduleId', 'dashboardId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_PERMANENTLY_DELETED,
    entityType: 'Conversation',
    defaultAction: 'permanentDelete',
    version: 1,
    description: 'Chat conversation permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'dashboardId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_SENT]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_SENT,
    entityType: 'Message',
    defaultAction: 'send',
    version: 1,
    description: 'Chat message sent.',
    recommendedMetadataFields: [
      'moduleId',
      'conversationId',
      'threadId',
      'attachmentCount',
      'hasAttachments',
    ],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_DELETED,
    entityType: 'Message',
    defaultAction: 'delete',
    version: 1,
    description: 'Chat message soft-deleted (in-chat trash).',
    recommendedMetadataFields: ['moduleId', 'conversationId', 'softDelete'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_RESTORED,
    entityType: 'Message',
    defaultAction: 'restore',
    version: 1,
    description: 'Chat message restored from in-chat trash.',
    recommendedMetadataFields: ['moduleId', 'conversationId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_PERMANENTLY_DELETED,
    entityType: 'Message',
    defaultAction: 'permanentDelete',
    version: 1,
    description: 'Chat message permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'conversationId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_REACTION_ADDED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_REACTION_ADDED,
    entityType: 'MessageReaction',
    defaultAction: 'react',
    version: 1,
    description: 'Reaction added to a chat message.',
    recommendedMetadataFields: ['moduleId', 'conversationId', 'messageId', 'emoji'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_READ]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_READ,
    entityType: 'ReadReceipt',
    defaultAction: 'read',
    version: 1,
    description: 'Chat message marked read.',
    recommendedMetadataFields: ['moduleId', 'conversationId', 'messageId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_CREATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_CREATED,
    entityType: 'Calendar',
    defaultAction: 'create',
    version: 1,
    description: 'Calendar created.',
    recommendedMetadataFields: ['moduleId', 'contextType'],
    disallowedMetadataFields: ['name', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_UPDATED,
    entityType: 'Calendar',
    defaultAction: 'update',
    version: 1,
    description: 'Calendar updated.',
    recommendedMetadataFields: ['moduleId', 'contextType'],
    disallowedMetadataFields: ['name', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_DELETED,
    entityType: 'Calendar',
    defaultAction: 'delete',
    version: 1,
    description: 'Calendar deleted.',
    recommendedMetadataFields: ['moduleId', 'contextType'],
    disallowedMetadataFields: ['name', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_CREATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_CREATED,
    entityType: 'CalendarEvent',
    defaultAction: 'create',
    version: 1,
    description: 'Calendar event created.',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'allDay', 'startAt', 'endAt'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_UPDATED,
    entityType: 'CalendarEvent',
    defaultAction: 'update',
    version: 1,
    description: 'Calendar event updated.',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'allDay', 'startAt', 'endAt'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_DELETED,
    entityType: 'CalendarEvent',
    defaultAction: 'delete',
    version: 1,
    description: 'Calendar event deleted or canceled (legacy; prefer trashed/permanentlyDeleted).',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'softDelete'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_TRASHED,
    entityType: 'CalendarEvent',
    defaultAction: 'trash',
    version: 1,
    description: 'Calendar event moved to trash.',
    recommendedMetadataFields: ['moduleId', 'calendarId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_RESTORED,
    entityType: 'CalendarEvent',
    defaultAction: 'restore',
    version: 1,
    description: 'Calendar event restored from trash.',
    recommendedMetadataFields: ['moduleId', 'calendarId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_PERMANENTLY_DELETED,
    entityType: 'CalendarEvent',
    defaultAction: 'permanentDelete',
    version: 1,
    description: 'Calendar event permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'calendarId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_RSVP_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_RSVP_UPDATED,
    entityType: 'EventAttendee',
    defaultAction: 'rsvp',
    version: 1,
    description: 'Calendar event RSVP response updated.',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'eventId', 'response'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_REMINDER_DISPATCHED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_REMINDER_DISPATCHED,
    entityType: 'Reminder',
    defaultAction: 'dispatch',
    version: 1,
    description: 'Calendar event reminder dispatched.',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'eventId', 'reminderId'],
    disallowedMetadataFields: ['title', 'body'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_CREATED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_CREATED,
    entityType: 'Task',
    defaultAction: 'create',
    version: 1,
    description: 'Todo task created.',
    recommendedMetadataFields: ['moduleId', 'status', 'priority'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_UPDATED,
    entityType: 'Task',
    defaultAction: 'update',
    version: 1,
    description: 'Todo task updated.',
    recommendedMetadataFields: ['moduleId', 'status', 'priority'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_COMPLETED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_COMPLETED,
    entityType: 'Task',
    defaultAction: 'complete',
    version: 1,
    description: 'Todo task marked complete.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_REOPENED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_REOPENED,
    entityType: 'Task',
    defaultAction: 'reopen',
    version: 1,
    description: 'Todo task reopened.',
    recommendedMetadataFields: ['moduleId', 'status'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_ASSIGNED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_ASSIGNED,
    entityType: 'Task',
    defaultAction: 'assign',
    version: 1,
    description: 'Todo task assigned to a user.',
    recommendedMetadataFields: ['moduleId', 'assigneeUserId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_UNASSIGNED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_UNASSIGNED,
    entityType: 'Task',
    defaultAction: 'unassign',
    version: 1,
    description: 'Todo task assignee cleared.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_TRASHED,
    entityType: 'Task',
    defaultAction: 'trash',
    version: 1,
    description: 'Todo task soft-trashed.',
    recommendedMetadataFields: ['moduleId', 'softDelete'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_RESTORED,
    entityType: 'Task',
    defaultAction: 'restore',
    version: 1,
    description: 'Todo task restored from trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_PERMANENTLY_DELETED,
    entityType: 'Task',
    defaultAction: 'permanently_delete',
    version: 1,
    description: 'Todo task permanently deleted from trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_CREATED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_CREATED,
    entityType: 'VLink',
    defaultAction: 'create',
    version: 1,
    description: 'V_Link container created.',
    recommendedMetadataFields: ['publicCode', 'scope', 'parentVLinkId'],
    disallowedMetadataFields: ['title', 'description'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_UPDATED,
    entityType: 'VLink',
    defaultAction: 'update',
    version: 1,
    description: 'V_Link container updated.',
    recommendedMetadataFields: ['changedFields'],
    disallowedMetadataFields: ['title', 'description'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_ARCHIVED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_ARCHIVED,
    entityType: 'VLink',
    defaultAction: 'archive',
    version: 1,
    description: 'V_Link archived.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.VLINK_DELETED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_DELETED,
    entityType: 'VLink',
    defaultAction: 'delete',
    version: 1,
    description: 'V_Link soft-deleted.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.VLINK_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_RESTORED,
    entityType: 'VLink',
    defaultAction: 'restore',
    version: 1,
    description: 'V_Link restored from archive.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.VLINK_MEMBER_ADDED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_MEMBER_ADDED,
    entityType: 'VLinkMember',
    defaultAction: 'add',
    version: 1,
    description: 'Member added to V_Link.',
    recommendedMetadataFields: ['memberUserId', 'role'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_MEMBER_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_MEMBER_UPDATED,
    entityType: 'VLinkMember',
    defaultAction: 'update',
    version: 1,
    description: 'V_Link member role updated.',
    recommendedMetadataFields: ['memberUserId', 'role'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_MEMBER_REMOVED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_MEMBER_REMOVED,
    entityType: 'VLinkMember',
    defaultAction: 'remove',
    version: 1,
    description: 'Member removed from V_Link.',
    recommendedMetadataFields: ['memberUserId'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_OWNERSHIP_TRANSFERRED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_OWNERSHIP_TRANSFERRED,
    entityType: 'VLink',
    defaultAction: 'transfer',
    version: 1,
    description: 'V_Link ownership transferred.',
    recommendedMetadataFields: ['fromUserId', 'toUserId'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_ENTITY_LINKED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_ENTITY_LINKED,
    entityType: 'VLinkEntity',
    defaultAction: 'link',
    version: 1,
    description: 'Entity linked to V_Link.',
    recommendedMetadataFields: ['entityType', 'linkedEntityId', 'moduleId', 'source'],
    disallowedMetadataFields: ['title', 'body', 'content'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_ENTITY_UNLINKED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_ENTITY_UNLINKED,
    entityType: 'VLinkEntity',
    defaultAction: 'unlink',
    version: 1,
    description: 'Entity unlinked from V_Link.',
    recommendedMetadataFields: ['entityType', 'linkedEntityId'],
    disallowedMetadataFields: ['title', 'body', 'content'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_CREATED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_CREATED,
    entityType: 'VLinkSuggestion',
    defaultAction: 'create',
    version: 1,
    description: 'AI/system V_Link suggestion created.',
    recommendedMetadataFields: ['entityType', 'linkedEntityId'],
    disallowedMetadataFields: ['explanation'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_ACCEPTED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_ACCEPTED,
    entityType: 'VLinkSuggestion',
    defaultAction: 'accept',
    version: 1,
    description: 'V_Link suggestion accepted by user.',
    recommendedMetadataFields: ['vlinkId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_REJECTED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_REJECTED,
    entityType: 'VLinkSuggestion',
    defaultAction: 'reject',
    version: 1,
    description: 'V_Link suggestion rejected by user.',
    recommendedMetadataFields: ['vlinkId'],
    disallowedMetadataFields: [],
  },
};

export function getDomainEventContract(type: string): DomainEventContract | undefined {
  return DOMAIN_EVENT_CONTRACTS[type as DomainEventType];
}

export function isRegisteredDomainEventType(type: string): type is DomainEventType {
  return type in DOMAIN_EVENT_CONTRACTS;
}

/** Strip sensitive / disallowed metadata keys before persistence and fan-out. */
export function sanitizeDomainEventMetadata(
  type: string,
  metadata: Record<string, unknown> | undefined
): Record<string, unknown> {
  if (!metadata) return {};
  const contract = getDomainEventContract(type);
  const disallowed = new Set<string>([
    ...GLOBAL_DISALLOWED_METADATA,
    ...(contract?.disallowedMetadataFields ?? []),
  ]);
  const sanitized: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(metadata)) {
    if (disallowed.has(key)) continue;
    if (val === undefined) continue;
    sanitized[key] = val;
  }
  return sanitized;
}

export type TypedDomainEventInput = Omit<DomainEventEmitInput, 'type' | 'entityType' | 'action'> & {
  entityType?: string;
  action?: string;
  metadata?: Record<string, unknown>;
};

/** Build emit input from registry contract (type-safe at call sites). */
export function buildTypedDomainEventInput(
  eventType: DomainEventType,
  input: TypedDomainEventInput
): DomainEventEmitInput {
  const contract = DOMAIN_EVENT_CONTRACTS[eventType];
  return {
    type: contract.type,
    actorUserId: input.actorUserId,
    dashboardId: input.dashboardId,
    businessId: input.businessId,
    householdId: input.householdId,
    entityType: input.entityType ?? contract.entityType,
    entityId: input.entityId,
    action: input.action ?? contract.defaultAction,
    metadata: sanitizeDomainEventMetadata(contract.type, input.metadata),
  };
}
