import type { DomainEventEmitInput } from './types';

/** Stable domain event type strings — use these instead of literals at emit sites. */
export const DOMAIN_EVENT_TYPES = {
  USER_PREFERENCE_UPDATED: 'user.preference.updated',
  SETTINGS_UPDATED: 'settings.updated',
  SETTINGS_THEME_CHANGED: 'settings.theme.changed',
  SETTINGS_PREFERENCE_CHANGED: 'settings.preference.changed',
  MODULE_INSTALLED: 'module.installed',
  MODULE_UNINSTALLED: 'module.uninstalled',
  MODULE_ENABLED: 'module.enabled',
  MODULE_DISABLED: 'module.disabled',
  BUSINESS_MEMBER_ADDED: 'business.member.added',
  BUSINESS_MEMBER_REMOVED: 'business.member.removed',
  BUSINESS_CREATED: 'business.created',
  BUSINESS_UPDATED: 'business.updated',
  FILE_UPLOADED: 'file.uploaded',
  FILE_DELETED: 'file.deleted',
  FILE_SHARED: 'file.shared',
  FILE_RENAMED: 'file.renamed',
  FILE_MOVED: 'file.moved',
  FILE_RESTORED: 'file.restored',
  FILE_UNSHARED: 'file.unshared',
  FOLDER_SHARED: 'folder.shared',
  FOLDER_CREATED: 'folder.created',
  FOLDER_RENAMED: 'folder.renamed',
  FOLDER_MOVED: 'folder.moved',
  FOLDER_DELETED: 'folder.deleted',
  FOLDER_RESTORED: 'folder.restored',
  FOLDER_UNSHARED: 'folder.unshared',
  CHAT_CONVERSATION_CREATED: 'chat.conversation.created',
  CHAT_CONVERSATION_TRASHED: 'chat.conversation.trashed',
  CHAT_CONVERSATION_RESTORED: 'chat.conversation.restored',
  CHAT_CONVERSATION_PERMANENTLY_DELETED: 'chat.conversation.permanentlyDeleted',
  CHAT_MESSAGE_SENT: 'chat.message.sent',
  CHAT_MESSAGE_DELETED: 'chat.message.deleted',
  CHAT_MESSAGE_RESTORED: 'chat.message.restored',
  CHAT_MESSAGE_PERMANENTLY_DELETED: 'chat.message.permanentlyDeleted',
  CHAT_MESSAGE_REACTION_ADDED: 'chat.message.reactionAdded',
  CHAT_MESSAGE_READ: 'chat.message.read',
  CALENDAR_CREATED: 'calendar.calendar.created',
  CALENDAR_UPDATED: 'calendar.calendar.updated',
  CALENDAR_DELETED: 'calendar.calendar.deleted',
  CALENDAR_EVENT_CREATED: 'calendar.event.created',
  CALENDAR_EVENT_UPDATED: 'calendar.event.updated',
  CALENDAR_EVENT_DELETED: 'calendar.event.deleted',
  CALENDAR_EVENT_TRASHED: 'calendar.event.trashed',
  CALENDAR_EVENT_RESTORED: 'calendar.event.restored',
  CALENDAR_EVENT_PERMANENTLY_DELETED: 'calendar.event.permanentlyDeleted',
  CALENDAR_EVENT_RSVP_UPDATED: 'calendar.event.rsvpUpdated',
  CALENDAR_EVENT_REMINDER_DISPATCHED: 'calendar.event.reminderDispatched',
  TODO_TASK_CREATED: 'todo.task.created',
  TODO_TASK_UPDATED: 'todo.task.updated',
  TODO_TASK_COMPLETED: 'todo.task.completed',
  TODO_TASK_REOPENED: 'todo.task.reopened',
  TODO_TASK_ASSIGNED: 'todo.task.assigned',
  TODO_TASK_UNASSIGNED: 'todo.task.unassigned',
  TODO_TASK_TRASHED: 'todo.task.trashed',
  TODO_TASK_RESTORED: 'todo.task.restored',
  TODO_TASK_PERMANENTLY_DELETED: 'todo.task.permanentlyDeleted',
  PLACE_NODE_ADDED: 'place.node.added',
  PLACE_NODE_UPDATED: 'place.node.updated',
  PLACE_NODE_REMOVED: 'place.node.removed',
  PLACE_INTERESTS_UPDATED: 'place.interests.updated',
  PLACE_FOLLOW_VISIBILITY_UPDATED: 'place.follow_visibility.updated',
  PLACE_LISTING_UPDATED: 'place.listing.updated',
  PLACE_LISTING_PUBLISHED: 'place.listing.published',
  PLACE_LISTING_REPORTED: 'place.listing.reported',
  PLACE_LISTING_TRASHED: 'place.listing.trashed',
  PLACE_LISTING_RESTORED: 'place.listing.restored',
  PLACE_LISTING_PERMANENTLY_DELETED: 'place.listing.permanentlyDeleted',
  PLACE_MEETING_CREATED: 'place.meeting.created',
  PLACE_MEETING_UPDATED: 'place.meeting.updated',
  PLACE_MEETING_CANCELLED: 'place.meeting.cancelled',
  PLACE_MEETING_RSVP_UPDATED: 'place.meeting.rsvp_updated',
  PLACE_MEETING_LINKED_TO_CALENDAR: 'place.meeting.linked_to_calendar',
  PLACE_MEETING_TRASHED: 'place.meeting.trashed',
  PLACE_MEETING_RESTORED: 'place.meeting.restored',
  PLACE_MEETING_PERMANENTLY_DELETED: 'place.meeting.permanentlyDeleted',
  PLACE_CONNECTION_REQUESTED: 'place.connection.requested',
  PLACE_CONNECTION_ACCEPTED: 'place.connection.accepted',
  PLACE_SETUP_COMPLETED: 'place.setup.completed',
  PLACE_COMMUNITY_CREATED: 'place.community.created',
  PLACE_COMMUNITY_JOINED: 'place.community.joined',
  PLACE_COMMUNITY_LEFT: 'place.community.left',
  PLACE_COMMUNITY_AUTO_CLUSTERED: 'place.community.auto_clustered',
  NOTES_PAGE_CREATED: 'notes.page.created',
  NOTES_PAGE_UPDATED: 'notes.page.updated',
  NOTES_PAGE_TRASHED: 'notes.page.trashed',
  NOTES_PAGE_RESTORED: 'notes.page.restored',
  NOTES_PAGE_PERMANENTLY_DELETED: 'notes.page.permanentlyDeleted',
  NOTES_PAGE_SHARED: 'notes.page.shared',
  NOTES_PAGE_UNSHARED: 'notes.page.unshared',
  NOTEBOOK_LINK_CREATED: 'notebook.link.created',
  NOTEBOOK_LINK_ARCHIVED: 'notebook.link.archived',
  VLINK_CREATED: 'vlink.created',
  VLINK_UPDATED: 'vlink.updated',
  VLINK_ARCHIVED: 'vlink.archived',
  VLINK_DELETED: 'vlink.deleted',
  VLINK_RESTORED: 'vlink.restored',
  VLINK_MEMBER_ADDED: 'vlink.member.added',
  VLINK_MEMBER_UPDATED: 'vlink.member.updated',
  VLINK_MEMBER_REMOVED: 'vlink.member.removed',
  VLINK_OWNERSHIP_TRANSFERRED: 'vlink.ownership.transferred',
  VLINK_ENTITY_LINKED: 'vlink.entity.linked',
  VLINK_ENTITY_UNLINKED: 'vlink.entity.unlinked',
  VLINK_SUGGESTION_CREATED: 'vlink.suggestion.created',
  VLINK_SUGGESTION_ACCEPTED: 'vlink.suggestion.accepted',
  VLINK_SUGGESTION_REJECTED: 'vlink.suggestion.rejected',
  SCHEDULING_SCHEDULE_CREATED: 'scheduling.schedule.created',
  SCHEDULING_SCHEDULE_UPDATED: 'scheduling.schedule.updated',
  SCHEDULING_SCHEDULE_PUBLISHED: 'scheduling.schedule.published',
  SCHEDULING_SCHEDULE_TRASHED: 'scheduling.schedule.trashed',
  SCHEDULING_SCHEDULE_RESTORED: 'scheduling.schedule.restored',
  SCHEDULING_SCHEDULE_PERMANENTLY_DELETED: 'scheduling.schedule.permanentlyDeleted',
  SCHEDULING_SHIFT_CREATED: 'scheduling.shift.created',
  SCHEDULING_SHIFT_UPDATED: 'scheduling.shift.updated',
  SCHEDULING_SHIFT_ASSIGNED: 'scheduling.shift.assigned',
  SCHEDULING_SHIFT_UNASSIGNED: 'scheduling.shift.unassigned',
  SCHEDULING_SHIFT_TRASHED: 'scheduling.shift.trashed',
  SCHEDULING_SHIFT_RESTORED: 'scheduling.shift.restored',
  SCHEDULING_SHIFT_PERMANENTLY_DELETED: 'scheduling.shift.permanentlyDeleted',
  SCHEDULING_SWAP_REQUESTED: 'scheduling.swap.requested',
  SCHEDULING_SWAP_RESOLVED: 'scheduling.swap.resolved',
  SCHEDULING_SHIFT_TEMPLATE_CREATED: 'scheduling.template.shift.created',
  SCHEDULING_SHIFT_TEMPLATE_UPDATED: 'scheduling.template.shift.updated',
  SCHEDULING_SHIFT_TEMPLATE_ARCHIVED: 'scheduling.template.shift.archived',
  SCHEDULING_SCHEDULE_TEMPLATE_CREATED: 'scheduling.template.schedule.created',
  SCHEDULING_SCHEDULE_TEMPLATE_UPDATED: 'scheduling.template.schedule.updated',
  SCHEDULING_SCHEDULE_TEMPLATE_TRASHED: 'scheduling.template.schedule.trashed',
  WORKFORCE_COMMUNICATION_CREATED: 'workforce.communication.created',
  WORKFORCE_COMMUNICATION_UPDATED: 'workforce.communication.updated',
  WORKFORCE_COMMUNICATION_SCHEDULED: 'workforce.communication.scheduled',
  WORKFORCE_COMMUNICATION_PUBLISHED: 'workforce.communication.published',
  WORKFORCE_COMMUNICATION_CANCELLED: 'workforce.communication.cancelled',
  WORKFORCE_COMMUNICATION_EXPIRED: 'workforce.communication.expired',
  WORKFORCE_COMMUNICATION_TRASHED: 'workforce.communication.trashed',
  WORKFORCE_COMMUNICATION_RESTORED: 'workforce.communication.restored',
  WORKFORCE_COMMUNICATION_PERMANENTLY_DELETED: 'workforce.communication.permanentlyDeleted',
  WORKFORCE_READ_RECORDED: 'workforce.read.recorded',
  WORKFORCE_ACK_COMPLETED: 'workforce.ack.completed',
  WORKFORCE_CAMPAIGN_CREATED: 'workforce.campaign.created',
  WORKFORCE_CAMPAIGN_COMPLETED: 'workforce.campaign.completed',
  WORKFORCE_CAMPAIGN_TRASHED: 'workforce.campaign.trashed',
  WORKFORCE_CAMPAIGN_RESTORED: 'workforce.campaign.restored',
  WORKFORCE_CAMPAIGN_PERMANENTLY_DELETED: 'workforce.campaign.permanentlyDeleted',
  WORKFORCE_BRIDGE_CREATED: 'workforce.bridge.created',
  HR_EMPLOYEE_CREATED: 'hr.employee.created',
  HR_EMPLOYEE_UPDATED: 'hr.employee.updated',
  HR_EMPLOYEE_TERMINATED: 'hr.employee.terminated',
  HR_EMPLOYEE_TRASHED: 'hr.employee.trashed',
  HR_EMPLOYEE_RESTORED: 'hr.employee.restored',
  HR_EMPLOYEE_PERMANENTLY_DELETED: 'hr.employee.permanentlyDeleted',
  HR_ONBOARDING_CREATED: 'hr.onboarding.created',
  HR_ONBOARDING_COMPLETED: 'hr.onboarding.completed',
  HR_PTO_REQUESTED: 'hr.pto.requested',
  HR_PTO_APPROVED: 'hr.pto.approved',
  HR_PTO_DENIED: 'hr.pto.denied',
  HR_ATTENDANCE_EXCEPTION_CREATED: 'hr.attendance.exception.created',
  ORGCHART_TIER_CREATED: 'orgchart.tier.created',
  ORGCHART_TIER_UPDATED: 'orgchart.tier.updated',
  ORGCHART_TIER_DELETED: 'orgchart.tier.deleted',
  ORGCHART_DEPARTMENT_CREATED: 'orgchart.department.created',
  ORGCHART_DEPARTMENT_UPDATED: 'orgchart.department.updated',
  ORGCHART_DEPARTMENT_DELETED: 'orgchart.department.deleted',
  ORGCHART_POSITION_CREATED: 'orgchart.position.created',
  ORGCHART_POSITION_UPDATED: 'orgchart.position.updated',
  ORGCHART_POSITION_DELETED: 'orgchart.position.deleted',
  ORGCHART_EMPLOYEE_ASSIGNED: 'orgchart.employee.assigned',
  ORGCHART_EMPLOYEE_REMOVED: 'orgchart.employee.removed',
  ORGCHART_EMPLOYEE_TRANSFERRED: 'orgchart.employee.transferred',
  ORGCHART_PERMISSION_SET_CREATED: 'orgchart.permission_set.created',
  ORGCHART_PERMISSION_UPDATED: 'orgchart.permission.updated',
  ORGCHART_PERMISSION_SET_DELETED: 'orgchart.permission_set.deleted',
  ORGCHART_PERMISSION_SET_COPIED: 'orgchart.permission_set.copied',
  ORGCHART_STRUCTURE_INITIALIZED: 'orgchart.structure.initialized',
  ORGCHART_MANAGER_ASSIGNED: 'orgchart.manager.assigned',
  ORGCHART_MANAGER_REMOVED: 'orgchart.manager.removed',
  APPROVAL_HIERARCHY_CREATED: 'approval_hierarchy.created',
  APPROVAL_HIERARCHY_UPDATED: 'approval_hierarchy.updated',
  APPROVAL_HIERARCHY_DELETED: 'approval_hierarchy.deleted',
  APPROVAL_HIERARCHY_ASSIGNED: 'approval_hierarchy.assigned',
  APPROVAL_HIERARCHY_VALIDATED: 'approval_hierarchy.validated',
  ENTITLEMENT_SUBSCRIPTION_TIER_CHANGED: 'entitlement.subscription_tier_changed',
  ENTITLEMENT_GRANTED: 'entitlement.granted',
  ENTITLEMENT_REVOKED: 'entitlement.revoked',
  ENTITLEMENT_BUSINESS_UPDATED: 'entitlement.business_updated',
  BILLING_SUBSCRIPTION_CREATED: 'billing.subscription_created',
  BILLING_SUBSCRIPTION_UPDATED: 'billing.subscription_updated',
  BILLING_SUBSCRIPTION_CANCELLED: 'billing.subscription_cancelled',
  BILLING_SUBSCRIPTION_RESUMED: 'billing.subscription_resumed',
  BILLING_SYNC_COMPLETED: 'billing.sync_completed',
  DASHBOARD_TAB_CREATED: 'dashboard.tab.created',
  DASHBOARD_TAB_DELETED: 'dashboard.tab.deleted',
  DASHBOARD_WIDGET_ADDED: 'dashboard.widget.added',
  DASHBOARD_WIDGET_REMOVED: 'dashboard.widget.removed',
} as const;

export type DomainEventType = (typeof DOMAIN_EVENT_TYPES)[keyof typeof DOMAIN_EVENT_TYPES];

export interface DomainEventContract {
  type: DomainEventType;
  entityType: string;
  defaultAction: string;
  version: number;
  description: string;
  recommendedMetadataFields: readonly string[];
  disallowedMetadataFields: readonly string[];
}

const GLOBAL_DISALLOWED_METADATA = [
  'password',
  'token',
  'secret',
  'accessToken',
  'refreshToken',
  'value',
  'rawValue',
  'configuration',
  'configured',
  'fileContent',
  'content',
  'body',
  'email',
] as const;

export const DOMAIN_EVENT_CONTRACTS: Record<DomainEventType, DomainEventContract> = {
  [DOMAIN_EVENT_TYPES.USER_PREFERENCE_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.USER_PREFERENCE_UPDATED,
    entityType: 'UserPreference',
    defaultAction: 'update',
    version: 1,
    description: 'User updated a preference key (value not included in metadata).',
    recommendedMetadataFields: ['key'],
    disallowedMetadataFields: ['value', 'rawValue'],
  },
  [DOMAIN_EVENT_TYPES.SETTINGS_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.SETTINGS_UPDATED,
    entityType: 'UserSettings',
    defaultAction: 'update',
    version: 1,
    description: 'Settings platform bulk or multi-key update.',
    recommendedMetadataFields: ['keys'],
    disallowedMetadataFields: ['value', 'values', 'settings'],
  },
  [DOMAIN_EVENT_TYPES.SETTINGS_THEME_CHANGED]: {
    type: DOMAIN_EVENT_TYPES.SETTINGS_THEME_CHANGED,
    entityType: 'UserPreference',
    defaultAction: 'update',
    version: 1,
    description: 'User changed appearance theme.',
    recommendedMetadataFields: ['theme'],
    disallowedMetadataFields: ['value'],
  },
  [DOMAIN_EVENT_TYPES.SETTINGS_PREFERENCE_CHANGED]: {
    type: DOMAIN_EVENT_TYPES.SETTINGS_PREFERENCE_CHANGED,
    entityType: 'UserPreference',
    defaultAction: 'update',
    version: 1,
    description: 'Settings platform updated a registered preference key.',
    recommendedMetadataFields: ['key'],
    disallowedMetadataFields: ['value'],
  },
  [DOMAIN_EVENT_TYPES.MODULE_INSTALLED]: {
    type: DOMAIN_EVENT_TYPES.MODULE_INSTALLED,
    entityType: 'ModuleInstallation',
    defaultAction: 'install',
    version: 1,
    description: 'Module installed for personal or business scope.',
    recommendedMetadataFields: ['moduleId', 'installScope', 'businessId', 'installationId'],
    disallowedMetadataFields: ['configured', 'configuration'],
  },
  [DOMAIN_EVENT_TYPES.MODULE_UNINSTALLED]: {
    type: DOMAIN_EVENT_TYPES.MODULE_UNINSTALLED,
    entityType: 'ModuleInstallation',
    defaultAction: 'uninstall',
    version: 1,
    description: 'Module uninstalled from personal or business scope.',
    recommendedMetadataFields: ['moduleId', 'installScope', 'businessId'],
    disallowedMetadataFields: ['configured', 'configuration'],
  },
  [DOMAIN_EVENT_TYPES.MODULE_ENABLED]: {
    type: DOMAIN_EVENT_TYPES.MODULE_ENABLED,
    entityType: 'ModuleInstallation',
    defaultAction: 'enable',
    version: 1,
    description: 'Module installation enabled.',
    recommendedMetadataFields: ['moduleId', 'installScope', 'businessId', 'installationId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.MODULE_DISABLED]: {
    type: DOMAIN_EVENT_TYPES.MODULE_DISABLED,
    entityType: 'ModuleInstallation',
    defaultAction: 'disable',
    version: 1,
    description: 'Module installation disabled.',
    recommendedMetadataFields: ['moduleId', 'installScope', 'businessId', 'installationId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.BUSINESS_MEMBER_ADDED]: {
    type: DOMAIN_EVENT_TYPES.BUSINESS_MEMBER_ADDED,
    entityType: 'BusinessMember',
    defaultAction: 'add',
    version: 1,
    description: 'User became an active business member.',
    recommendedMetadataFields: ['memberUserId', 'role'],
    disallowedMetadataFields: ['email', 'token'],
  },
  [DOMAIN_EVENT_TYPES.BUSINESS_MEMBER_REMOVED]: {
    type: DOMAIN_EVENT_TYPES.BUSINESS_MEMBER_REMOVED,
    entityType: 'BusinessMember',
    defaultAction: 'remove',
    version: 1,
    description: 'User removed from business (adopted on remove member paths).',
    recommendedMetadataFields: ['memberUserId', 'role'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.BUSINESS_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.BUSINESS_UPDATED,
    entityType: 'Business',
    defaultAction: 'update',
    version: 1,
    description: 'Business profile or branding updated.',
    recommendedMetadataFields: ['changedFields', 'updateKind'],
    disallowedMetadataFields: [
      'ein',
      'logo',
      'logoUrl',
      'settings',
      'manifest',
      'configuration',
      'configured',
      'website',
      'description',
    ],
  },
  [DOMAIN_EVENT_TYPES.BUSINESS_CREATED]: {
    type: DOMAIN_EVENT_TYPES.BUSINESS_CREATED,
    entityType: 'Business',
    defaultAction: 'create',
    version: 1,
    description: 'Business profile created.',
    recommendedMetadataFields: ['name'],
    disallowedMetadataFields: ['ein', 'logo', 'logoUrl', 'settings', 'configuration', 'configured'],
  },
  [DOMAIN_EVENT_TYPES.FILE_UPLOADED]: {
    type: DOMAIN_EVENT_TYPES.FILE_UPLOADED,
    entityType: 'File',
    defaultAction: 'upload',
    version: 1,
    description: 'File uploaded to Drive.',
    recommendedMetadataFields: ['folderId', 'fileType', 'sizeBytes', 'dashboardId'],
    disallowedMetadataFields: ['content', 'fileContent', 'url', 'path', 'signedUrl'],
  },
  [DOMAIN_EVENT_TYPES.FILE_DELETED]: {
    type: DOMAIN_EVENT_TYPES.FILE_DELETED,
    entityType: 'File',
    defaultAction: 'delete',
    version: 1,
    description: 'File moved to trash or removed from Drive.',
    recommendedMetadataFields: ['folderId', 'softDelete', 'dashboardId'],
    disallowedMetadataFields: ['content', 'url', 'path', 'signedUrl'],
  },
  [DOMAIN_EVENT_TYPES.FILE_SHARED]: {
    type: DOMAIN_EVENT_TYPES.FILE_SHARED,
    entityType: 'File',
    defaultAction: 'share',
    version: 1,
    description: 'File permission granted to another user.',
    recommendedMetadataFields: ['recipientUserId', 'canRead', 'canWrite', 'shareRole'],
    disallowedMetadataFields: ['url', 'path', 'signedUrl', 'email'],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_SHARED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_SHARED,
    entityType: 'Folder',
    defaultAction: 'share',
    version: 1,
    description: 'Folder permission granted to another user.',
    recommendedMetadataFields: ['recipientUserId', 'canRead', 'canWrite', 'shareRole'],
    disallowedMetadataFields: ['url', 'path', 'signedUrl', 'email'],
  },
  [DOMAIN_EVENT_TYPES.FILE_RENAMED]: {
    type: DOMAIN_EVENT_TYPES.FILE_RENAMED,
    entityType: 'File',
    defaultAction: 'rename',
    version: 1,
    description: 'File renamed in File Hub.',
    recommendedMetadataFields: ['fileName', 'previousName', 'folderId', 'dashboardId'],
    disallowedMetadataFields: ['content', 'url', 'path'],
  },
  [DOMAIN_EVENT_TYPES.FILE_MOVED]: {
    type: DOMAIN_EVENT_TYPES.FILE_MOVED,
    entityType: 'File',
    defaultAction: 'move',
    version: 1,
    description: 'File moved to another folder.',
    recommendedMetadataFields: ['folderId', 'previousFolderId', 'dashboardId', 'fileName'],
    disallowedMetadataFields: ['content', 'url', 'path'],
  },
  [DOMAIN_EVENT_TYPES.FILE_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.FILE_RESTORED,
    entityType: 'File',
    defaultAction: 'restore',
    version: 1,
    description: 'File restored from trash.',
    recommendedMetadataFields: ['folderId', 'dashboardId', 'fileName'],
    disallowedMetadataFields: ['content', 'url', 'path'],
  },
  [DOMAIN_EVENT_TYPES.FILE_UNSHARED]: {
    type: DOMAIN_EVENT_TYPES.FILE_UNSHARED,
    entityType: 'File',
    defaultAction: 'unshare',
    version: 1,
    description: 'File share permission revoked.',
    recommendedMetadataFields: ['recipientUserId', 'fileName', 'dashboardId'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_CREATED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_CREATED,
    entityType: 'Folder',
    defaultAction: 'create',
    version: 1,
    description: 'Folder created in File Hub.',
    recommendedMetadataFields: ['parentId', 'dashboardId', 'folderName'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_RENAMED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_RENAMED,
    entityType: 'Folder',
    defaultAction: 'rename',
    version: 1,
    description: 'Folder renamed in File Hub.',
    recommendedMetadataFields: ['folderName', 'previousName', 'parentId', 'dashboardId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_MOVED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_MOVED,
    entityType: 'Folder',
    defaultAction: 'move',
    version: 1,
    description: 'Folder moved to another parent.',
    recommendedMetadataFields: ['parentId', 'previousParentId', 'dashboardId', 'folderName'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_DELETED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_DELETED,
    entityType: 'Folder',
    defaultAction: 'delete',
    version: 1,
    description: 'Folder moved to trash or permanently deleted.',
    recommendedMetadataFields: ['parentId', 'softDelete', 'dashboardId', 'folderName'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_RESTORED,
    entityType: 'Folder',
    defaultAction: 'restore',
    version: 1,
    description: 'Folder restored from trash.',
    recommendedMetadataFields: ['parentId', 'dashboardId', 'folderName'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.FOLDER_UNSHARED]: {
    type: DOMAIN_EVENT_TYPES.FOLDER_UNSHARED,
    entityType: 'Folder',
    defaultAction: 'unshare',
    version: 1,
    description: 'Folder share permission revoked.',
    recommendedMetadataFields: ['recipientUserId', 'folderName', 'dashboardId'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_CREATED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_CREATED,
    entityType: 'Conversation',
    defaultAction: 'create',
    version: 1,
    description: 'Chat conversation created.',
    recommendedMetadataFields: ['moduleId', 'conversationType', 'dashboardId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_TRASHED,
    entityType: 'Conversation',
    defaultAction: 'trash',
    version: 1,
    description: 'Chat conversation moved to trash.',
    recommendedMetadataFields: ['moduleId', 'dashboardId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_RESTORED,
    entityType: 'Conversation',
    defaultAction: 'restore',
    version: 1,
    description: 'Chat conversation restored from trash.',
    recommendedMetadataFields: ['moduleId', 'dashboardId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_CONVERSATION_PERMANENTLY_DELETED,
    entityType: 'Conversation',
    defaultAction: 'permanentDelete',
    version: 1,
    description: 'Chat conversation permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'dashboardId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_SENT]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_SENT,
    entityType: 'Message',
    defaultAction: 'send',
    version: 1,
    description: 'Chat message sent.',
    recommendedMetadataFields: [
      'moduleId',
      'conversationId',
      'threadId',
      'attachmentCount',
      'hasAttachments',
    ],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_DELETED,
    entityType: 'Message',
    defaultAction: 'delete',
    version: 1,
    description: 'Chat message soft-deleted (in-chat trash).',
    recommendedMetadataFields: ['moduleId', 'conversationId', 'softDelete'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_RESTORED,
    entityType: 'Message',
    defaultAction: 'restore',
    version: 1,
    description: 'Chat message restored from in-chat trash.',
    recommendedMetadataFields: ['moduleId', 'conversationId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_PERMANENTLY_DELETED,
    entityType: 'Message',
    defaultAction: 'permanentDelete',
    version: 1,
    description: 'Chat message permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'conversationId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_REACTION_ADDED]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_REACTION_ADDED,
    entityType: 'MessageReaction',
    defaultAction: 'react',
    version: 1,
    description: 'Reaction added to a chat message.',
    recommendedMetadataFields: ['moduleId', 'conversationId', 'messageId', 'emoji'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CHAT_MESSAGE_READ]: {
    type: DOMAIN_EVENT_TYPES.CHAT_MESSAGE_READ,
    entityType: 'ReadReceipt',
    defaultAction: 'read',
    version: 1,
    description: 'Chat message marked read.',
    recommendedMetadataFields: ['moduleId', 'conversationId', 'messageId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_CREATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_CREATED,
    entityType: 'Calendar',
    defaultAction: 'create',
    version: 1,
    description: 'Calendar created.',
    recommendedMetadataFields: ['moduleId', 'contextType'],
    disallowedMetadataFields: ['name', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_UPDATED,
    entityType: 'Calendar',
    defaultAction: 'update',
    version: 1,
    description: 'Calendar updated.',
    recommendedMetadataFields: ['moduleId', 'contextType'],
    disallowedMetadataFields: ['name', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_DELETED,
    entityType: 'Calendar',
    defaultAction: 'delete',
    version: 1,
    description: 'Calendar deleted.',
    recommendedMetadataFields: ['moduleId', 'contextType'],
    disallowedMetadataFields: ['name', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_CREATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_CREATED,
    entityType: 'CalendarEvent',
    defaultAction: 'create',
    version: 1,
    description: 'Calendar event created.',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'allDay', 'startAt', 'endAt'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_UPDATED,
    entityType: 'CalendarEvent',
    defaultAction: 'update',
    version: 1,
    description: 'Calendar event updated.',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'allDay', 'startAt', 'endAt'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_DELETED,
    entityType: 'CalendarEvent',
    defaultAction: 'delete',
    version: 1,
    description: 'Calendar event deleted or canceled (legacy; prefer trashed/permanentlyDeleted).',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'softDelete'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_TRASHED,
    entityType: 'CalendarEvent',
    defaultAction: 'trash',
    version: 1,
    description: 'Calendar event moved to trash.',
    recommendedMetadataFields: ['moduleId', 'calendarId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_RESTORED,
    entityType: 'CalendarEvent',
    defaultAction: 'restore',
    version: 1,
    description: 'Calendar event restored from trash.',
    recommendedMetadataFields: ['moduleId', 'calendarId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_PERMANENTLY_DELETED,
    entityType: 'CalendarEvent',
    defaultAction: 'permanentDelete',
    version: 1,
    description: 'Calendar event permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'calendarId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_RSVP_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_RSVP_UPDATED,
    entityType: 'EventAttendee',
    defaultAction: 'rsvp',
    version: 1,
    description: 'Calendar event RSVP response updated.',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'eventId', 'response'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.CALENDAR_EVENT_REMINDER_DISPATCHED]: {
    type: DOMAIN_EVENT_TYPES.CALENDAR_EVENT_REMINDER_DISPATCHED,
    entityType: 'Reminder',
    defaultAction: 'dispatch',
    version: 1,
    description: 'Calendar event reminder dispatched.',
    recommendedMetadataFields: ['moduleId', 'calendarId', 'eventId', 'reminderId'],
    disallowedMetadataFields: ['title', 'body'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_CREATED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_CREATED,
    entityType: 'Task',
    defaultAction: 'create',
    version: 1,
    description: 'Todo task created.',
    recommendedMetadataFields: ['moduleId', 'status', 'priority'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_UPDATED,
    entityType: 'Task',
    defaultAction: 'update',
    version: 1,
    description: 'Todo task updated.',
    recommendedMetadataFields: ['moduleId', 'status', 'priority'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_COMPLETED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_COMPLETED,
    entityType: 'Task',
    defaultAction: 'complete',
    version: 1,
    description: 'Todo task marked complete.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_REOPENED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_REOPENED,
    entityType: 'Task',
    defaultAction: 'reopen',
    version: 1,
    description: 'Todo task reopened.',
    recommendedMetadataFields: ['moduleId', 'status'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_ASSIGNED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_ASSIGNED,
    entityType: 'Task',
    defaultAction: 'assign',
    version: 1,
    description: 'Todo task assigned to a user.',
    recommendedMetadataFields: ['moduleId', 'assigneeUserId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_UNASSIGNED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_UNASSIGNED,
    entityType: 'Task',
    defaultAction: 'unassign',
    version: 1,
    description: 'Todo task assignee cleared.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_TRASHED,
    entityType: 'Task',
    defaultAction: 'trash',
    version: 1,
    description: 'Todo task soft-trashed.',
    recommendedMetadataFields: ['moduleId', 'softDelete'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_RESTORED,
    entityType: 'Task',
    defaultAction: 'restore',
    version: 1,
    description: 'Todo task restored from trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.TODO_TASK_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.TODO_TASK_PERMANENTLY_DELETED,
    entityType: 'Task',
    defaultAction: 'permanently_delete',
    version: 1,
    description: 'Todo task permanently deleted from trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_NODE_ADDED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_NODE_ADDED,
    entityType: 'PlaceNode',
    defaultAction: 'create',
    version: 1,
    description: 'Place graph node added.',
    recommendedMetadataFields: ['moduleId', 'nodeType', 'entityId'],
    disallowedMetadataFields: ['label'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_NODE_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_NODE_UPDATED,
    entityType: 'PlaceNode',
    defaultAction: 'update',
    version: 1,
    description: 'Place graph node layout or label updated.',
    recommendedMetadataFields: ['moduleId', 'nodeType', 'entityId'],
    disallowedMetadataFields: ['label'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_NODE_REMOVED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_NODE_REMOVED,
    entityType: 'PlaceNode',
    defaultAction: 'delete',
    version: 1,
    description: 'Place graph node removed.',
    recommendedMetadataFields: ['moduleId', 'nodeType', 'entityId'],
    disallowedMetadataFields: ['label'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_LISTING_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_LISTING_UPDATED,
    entityType: 'BusinessPlaceListing',
    defaultAction: 'update',
    version: 1,
    description: 'Business Place listing updated.',
    recommendedMetadataFields: ['moduleId', 'businessId'],
    disallowedMetadataFields: ['shortDescription', 'displayName'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_LISTING_PUBLISHED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_LISTING_PUBLISHED,
    entityType: 'BusinessPlaceListing',
    defaultAction: 'publish',
    version: 1,
    description: 'Business Place listing published.',
    recommendedMetadataFields: ['moduleId', 'businessId'],
    disallowedMetadataFields: ['shortDescription', 'displayName'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_LISTING_REPORTED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_LISTING_REPORTED,
    entityType: 'BusinessPlaceListing',
    defaultAction: 'report',
    version: 1,
    description: 'Business Place listing reported for moderation.',
    recommendedMetadataFields: ['moduleId', 'businessId', 'reason'],
    disallowedMetadataFields: ['details'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_LISTING_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_LISTING_TRASHED,
    entityType: 'BusinessPlaceListing',
    defaultAction: 'trash',
    version: 1,
    description: 'Business Place listing moved to trash.',
    recommendedMetadataFields: ['moduleId', 'businessId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_LISTING_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_LISTING_RESTORED,
    entityType: 'BusinessPlaceListing',
    defaultAction: 'restore',
    version: 1,
    description: 'Business Place listing restored from trash.',
    recommendedMetadataFields: ['moduleId', 'businessId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_LISTING_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_LISTING_PERMANENTLY_DELETED,
    entityType: 'BusinessPlaceListing',
    defaultAction: 'permanentlyDelete',
    version: 1,
    description: 'Business Place listing permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'businessId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_MEETING_CREATED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_MEETING_CREATED,
    entityType: 'PlaceMeetingPlace',
    defaultAction: 'create',
    version: 1,
    description: 'Place meeting created.',
    recommendedMetadataFields: ['moduleId', 'locationName'],
    disallowedMetadataFields: ['note', 'locationAddress'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_MEETING_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_MEETING_UPDATED,
    entityType: 'PlaceMeetingPlace',
    defaultAction: 'update',
    version: 1,
    description: 'Place meeting updated.',
    recommendedMetadataFields: ['moduleId', 'status'],
    disallowedMetadataFields: ['note', 'locationAddress'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_MEETING_CANCELLED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_MEETING_CANCELLED,
    entityType: 'PlaceMeetingPlace',
    defaultAction: 'cancel',
    version: 1,
    description: 'Place meeting cancelled.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['note'],
  },
  [DOMAIN_EVENT_TYPES.PLACE_MEETING_RSVP_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_MEETING_RSVP_UPDATED,
    entityType: 'PlaceMeetingInvite',
    defaultAction: 'rsvp',
    version: 1,
    description: 'Place meeting RSVP updated.',
    recommendedMetadataFields: ['moduleId', 'meetingId', 'rsvpStatus'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_MEETING_LINKED_TO_CALENDAR]: {
    type: DOMAIN_EVENT_TYPES.PLACE_MEETING_LINKED_TO_CALENDAR,
    entityType: 'PlaceMeetingPlace',
    defaultAction: 'link_calendar',
    version: 1,
    description: 'Place meeting linked to a calendar event.',
    recommendedMetadataFields: ['moduleId', 'eventId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_MEETING_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_MEETING_TRASHED,
    entityType: 'PlaceMeetingPlace',
    defaultAction: 'trash',
    version: 1,
    description: 'Place meeting moved to trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_MEETING_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_MEETING_RESTORED,
    entityType: 'PlaceMeetingPlace',
    defaultAction: 'restore',
    version: 1,
    description: 'Place meeting restored from trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_MEETING_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_MEETING_PERMANENTLY_DELETED,
    entityType: 'PlaceMeetingPlace',
    defaultAction: 'permanentlyDelete',
    version: 1,
    description: 'Place meeting permanently deleted.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_CONNECTION_REQUESTED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_CONNECTION_REQUESTED,
    entityType: 'Relationship',
    defaultAction: 'request',
    version: 1,
    description: 'Place connection request sent.',
    recommendedMetadataFields: ['moduleId', 'targetUserId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_CONNECTION_ACCEPTED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_CONNECTION_ACCEPTED,
    entityType: 'Relationship',
    defaultAction: 'accept',
    version: 1,
    description: 'Place connection accepted and nodes mirrored.',
    recommendedMetadataFields: ['moduleId', 'withUserId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_SETUP_COMPLETED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_SETUP_COMPLETED,
    entityType: 'Place',
    defaultAction: 'complete_setup',
    version: 1,
    description: 'Place onboarding setup completed.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_INTERESTS_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_INTERESTS_UPDATED,
    entityType: 'Place',
    defaultAction: 'update',
    version: 1,
    description: 'Place interest categories updated.',
    recommendedMetadataFields: ['moduleId', 'categories'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_FOLLOW_VISIBILITY_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_FOLLOW_VISIBILITY_UPDATED,
    entityType: 'PlaceFollowVisibility',
    defaultAction: 'update',
    version: 1,
    description: 'Place follow visibility preference updated.',
    recommendedMetadataFields: ['moduleId', 'businessId', 'isVisible'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_COMMUNITY_CREATED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_COMMUNITY_CREATED,
    entityType: 'PlaceCommunity',
    defaultAction: 'create',
    version: 1,
    description: 'Place community created.',
    recommendedMetadataFields: ['moduleId', 'communityName'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_COMMUNITY_JOINED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_COMMUNITY_JOINED,
    entityType: 'PlaceCommunity',
    defaultAction: 'join',
    version: 1,
    description: 'User joined a Place community.',
    recommendedMetadataFields: ['moduleId', 'communityId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_COMMUNITY_LEFT]: {
    type: DOMAIN_EVENT_TYPES.PLACE_COMMUNITY_LEFT,
    entityType: 'PlaceCommunity',
    defaultAction: 'leave',
    version: 1,
    description: 'User left a Place community.',
    recommendedMetadataFields: ['moduleId', 'communityId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.PLACE_COMMUNITY_AUTO_CLUSTERED]: {
    type: DOMAIN_EVENT_TYPES.PLACE_COMMUNITY_AUTO_CLUSTERED,
    entityType: 'PlaceCommunity',
    defaultAction: 'auto_cluster',
    version: 1,
    description: 'Auto-cluster communities generated from shared Place graph.',
    recommendedMetadataFields: ['moduleId', 'clustersCreated'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.NOTES_PAGE_CREATED]: {
    type: DOMAIN_EVENT_TYPES.NOTES_PAGE_CREATED,
    entityType: 'Page',
    defaultAction: 'create',
    version: 1,
    description: 'Notebook page (Note) created.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['content', 'body', 'description'],
  },
  [DOMAIN_EVENT_TYPES.NOTES_PAGE_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.NOTES_PAGE_UPDATED,
    entityType: 'Page',
    defaultAction: 'update',
    version: 1,
    description: 'Notebook page (Note) updated.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['content', 'body', 'description'],
  },
  [DOMAIN_EVENT_TYPES.NOTES_PAGE_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.NOTES_PAGE_TRASHED,
    entityType: 'Page',
    defaultAction: 'trash',
    version: 1,
    description: 'Notebook page soft-trashed.',
    recommendedMetadataFields: ['moduleId', 'softDelete'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.NOTES_PAGE_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.NOTES_PAGE_RESTORED,
    entityType: 'Page',
    defaultAction: 'restore',
    version: 1,
    description: 'Notebook page restored from trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.NOTES_PAGE_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.NOTES_PAGE_PERMANENTLY_DELETED,
    entityType: 'Page',
    defaultAction: 'permanently_delete',
    version: 1,
    description: 'Notebook page permanently deleted.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['content', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.NOTES_PAGE_SHARED]: {
    type: DOMAIN_EVENT_TYPES.NOTES_PAGE_SHARED,
    entityType: 'Page',
    defaultAction: 'share',
    version: 1,
    description: 'Notebook page shared with another user.',
    recommendedMetadataFields: ['moduleId', 'sharedWithUserId', 'role'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.NOTES_PAGE_UNSHARED]: {
    type: DOMAIN_EVENT_TYPES.NOTES_PAGE_UNSHARED,
    entityType: 'Page',
    defaultAction: 'unshare',
    version: 1,
    description: 'Notebook page share revoked.',
    recommendedMetadataFields: ['moduleId', 'sharedWithUserId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.NOTEBOOK_LINK_CREATED]: {
    type: DOMAIN_EVENT_TYPES.NOTEBOOK_LINK_CREATED,
    entityType: 'NotebookLink',
    defaultAction: 'create',
    version: 1,
    description: 'Operational NotebookLink created (page-centric).',
    recommendedMetadataFields: ['moduleId', 'pageId', 'targetType', 'targetId', 'relationshipType'],
    disallowedMetadataFields: ['content', 'body', 'promotedText'],
  },
  [DOMAIN_EVENT_TYPES.NOTEBOOK_LINK_ARCHIVED]: {
    type: DOMAIN_EVENT_TYPES.NOTEBOOK_LINK_ARCHIVED,
    entityType: 'NotebookLink',
    defaultAction: 'archive',
    version: 1,
    description: 'Operational NotebookLink archived (soft remove).',
    recommendedMetadataFields: ['moduleId', 'pageId', 'targetType', 'targetId'],
    disallowedMetadataFields: ['content', 'body'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_CREATED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_CREATED,
    entityType: 'VLink',
    defaultAction: 'create',
    version: 1,
    description: 'V_Link container created.',
    recommendedMetadataFields: ['publicCode', 'scope', 'parentVLinkId'],
    disallowedMetadataFields: ['title', 'description'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_UPDATED,
    entityType: 'VLink',
    defaultAction: 'update',
    version: 1,
    description: 'V_Link container updated.',
    recommendedMetadataFields: ['changedFields'],
    disallowedMetadataFields: ['title', 'description'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_ARCHIVED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_ARCHIVED,
    entityType: 'VLink',
    defaultAction: 'archive',
    version: 1,
    description: 'V_Link archived.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.VLINK_DELETED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_DELETED,
    entityType: 'VLink',
    defaultAction: 'delete',
    version: 1,
    description: 'V_Link soft-deleted.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.VLINK_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_RESTORED,
    entityType: 'VLink',
    defaultAction: 'restore',
    version: 1,
    description: 'V_Link restored from archive.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.VLINK_MEMBER_ADDED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_MEMBER_ADDED,
    entityType: 'VLinkMember',
    defaultAction: 'add',
    version: 1,
    description: 'Member added to V_Link.',
    recommendedMetadataFields: ['memberUserId', 'role'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_MEMBER_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_MEMBER_UPDATED,
    entityType: 'VLinkMember',
    defaultAction: 'update',
    version: 1,
    description: 'V_Link member role updated.',
    recommendedMetadataFields: ['memberUserId', 'role'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_MEMBER_REMOVED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_MEMBER_REMOVED,
    entityType: 'VLinkMember',
    defaultAction: 'remove',
    version: 1,
    description: 'Member removed from V_Link.',
    recommendedMetadataFields: ['memberUserId'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_OWNERSHIP_TRANSFERRED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_OWNERSHIP_TRANSFERRED,
    entityType: 'VLink',
    defaultAction: 'transfer',
    version: 1,
    description: 'V_Link ownership transferred.',
    recommendedMetadataFields: ['fromUserId', 'toUserId'],
    disallowedMetadataFields: ['email'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_ENTITY_LINKED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_ENTITY_LINKED,
    entityType: 'VLinkEntity',
    defaultAction: 'link',
    version: 1,
    description: 'Entity linked to V_Link.',
    recommendedMetadataFields: ['entityType', 'linkedEntityId', 'moduleId', 'source'],
    disallowedMetadataFields: ['title', 'body', 'content'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_ENTITY_UNLINKED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_ENTITY_UNLINKED,
    entityType: 'VLinkEntity',
    defaultAction: 'unlink',
    version: 1,
    description: 'Entity unlinked from V_Link.',
    recommendedMetadataFields: ['entityType', 'linkedEntityId'],
    disallowedMetadataFields: ['title', 'body', 'content'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_CREATED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_CREATED,
    entityType: 'VLinkSuggestion',
    defaultAction: 'create',
    version: 1,
    description: 'AI/system V_Link suggestion created.',
    recommendedMetadataFields: ['entityType', 'linkedEntityId'],
    disallowedMetadataFields: ['explanation'],
  },
  [DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_ACCEPTED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_ACCEPTED,
    entityType: 'VLinkSuggestion',
    defaultAction: 'accept',
    version: 1,
    description: 'V_Link suggestion accepted by user.',
    recommendedMetadataFields: ['vlinkId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_REJECTED]: {
    type: DOMAIN_EVENT_TYPES.VLINK_SUGGESTION_REJECTED,
    entityType: 'VLinkSuggestion',
    defaultAction: 'reject',
    version: 1,
    description: 'V_Link suggestion rejected by user.',
    recommendedMetadataFields: ['vlinkId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_CREATED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_CREATED,
    entityType: 'Schedule',
    defaultAction: 'create',
    version: 1,
    description: 'Scheduling schedule created.',
    recommendedMetadataFields: ['moduleId', 'status'],
    disallowedMetadataFields: ['name', 'description', 'title', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_UPDATED,
    entityType: 'Schedule',
    defaultAction: 'update',
    version: 1,
    description: 'Scheduling schedule updated.',
    recommendedMetadataFields: ['moduleId', 'status'],
    disallowedMetadataFields: ['name', 'description', 'title', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_PUBLISHED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_PUBLISHED,
    entityType: 'Schedule',
    defaultAction: 'publish',
    version: 1,
    description: 'Scheduling schedule published.',
    recommendedMetadataFields: ['moduleId', 'shiftCount'],
    disallowedMetadataFields: ['name', 'description', 'title', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_TRASHED,
    entityType: 'Schedule',
    defaultAction: 'trash',
    version: 1,
    description: 'Scheduling schedule soft-trashed.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'title', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_RESTORED,
    entityType: 'Schedule',
    defaultAction: 'restore',
    version: 1,
    description: 'Scheduling schedule restored from trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'title', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_PERMANENTLY_DELETED,
    entityType: 'Schedule',
    defaultAction: 'purge',
    version: 1,
    description: 'Scheduling schedule permanently deleted.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'title', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_CREATED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_CREATED,
    entityType: 'ScheduleShift',
    defaultAction: 'create',
    version: 1,
    description: 'Scheduling shift created.',
    recommendedMetadataFields: ['moduleId', 'scheduleId', 'status'],
    disallowedMetadataFields: ['title', 'notes', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_UPDATED,
    entityType: 'ScheduleShift',
    defaultAction: 'update',
    version: 1,
    description: 'Scheduling shift updated.',
    recommendedMetadataFields: ['moduleId', 'scheduleId', 'status'],
    disallowedMetadataFields: ['title', 'notes', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_ASSIGNED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_ASSIGNED,
    entityType: 'ScheduleShift',
    defaultAction: 'assign',
    version: 1,
    description: 'Scheduling shift assigned to employee position.',
    recommendedMetadataFields: ['moduleId', 'scheduleId', 'employeePositionId'],
    disallowedMetadataFields: ['title', 'notes', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_UNASSIGNED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_UNASSIGNED,
    entityType: 'ScheduleShift',
    defaultAction: 'unassign',
    version: 1,
    description: 'Scheduling shift assignee cleared.',
    recommendedMetadataFields: ['moduleId', 'scheduleId', 'employeePositionId'],
    disallowedMetadataFields: ['title', 'notes', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_TRASHED,
    entityType: 'ScheduleShift',
    defaultAction: 'trash',
    version: 1,
    description: 'Scheduling shift soft-trashed.',
    recommendedMetadataFields: ['moduleId', 'scheduleId'],
    disallowedMetadataFields: ['title', 'notes', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_RESTORED,
    entityType: 'ScheduleShift',
    defaultAction: 'restore',
    version: 1,
    description: 'Scheduling shift restored from trash.',
    recommendedMetadataFields: ['moduleId', 'scheduleId'],
    disallowedMetadataFields: ['title', 'notes', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_PERMANENTLY_DELETED,
    entityType: 'ScheduleShift',
    defaultAction: 'purge',
    version: 1,
    description: 'Scheduling shift permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'scheduleId'],
    disallowedMetadataFields: ['title', 'notes', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SWAP_REQUESTED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SWAP_REQUESTED,
    entityType: 'ShiftSwapRequest',
    defaultAction: 'request',
    version: 1,
    description: 'Shift swap requested.',
    recommendedMetadataFields: ['moduleId', 'shiftId', 'requestedToId'],
    disallowedMetadataFields: ['reason', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SWAP_RESOLVED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SWAP_RESOLVED,
    entityType: 'ShiftSwapRequest',
    defaultAction: 'resolve',
    version: 1,
    description: 'Shift swap resolved (approved or denied).',
    recommendedMetadataFields: ['moduleId', 'shiftId', 'outcome'],
    disallowedMetadataFields: ['reason', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_TEMPLATE_CREATED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_TEMPLATE_CREATED,
    entityType: 'ShiftTemplate',
    defaultAction: 'create',
    version: 1,
    description: 'Shift template created.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_TEMPLATE_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_TEMPLATE_UPDATED,
    entityType: 'ShiftTemplate',
    defaultAction: 'update',
    version: 1,
    description: 'Shift template updated.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_TEMPLATE_ARCHIVED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SHIFT_TEMPLATE_ARCHIVED,
    entityType: 'ShiftTemplate',
    defaultAction: 'archive',
    version: 1,
    description: 'Shift template archived.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_TEMPLATE_CREATED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_TEMPLATE_CREATED,
    entityType: 'ScheduleTemplate',
    defaultAction: 'create',
    version: 1,
    description: 'Schedule template created.',
    recommendedMetadataFields: ['moduleId', 'scheduleType'],
    disallowedMetadataFields: ['name', 'description', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_TEMPLATE_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_TEMPLATE_UPDATED,
    entityType: 'ScheduleTemplate',
    defaultAction: 'update',
    version: 1,
    description: 'Schedule template updated.',
    recommendedMetadataFields: ['moduleId', 'scheduleType'],
    disallowedMetadataFields: ['name', 'description', 'body'],
  },
  [DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_TEMPLATE_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.SCHEDULING_SCHEDULE_TEMPLATE_TRASHED,
    entityType: 'ScheduleTemplate',
    defaultAction: 'trash',
    version: 1,
    description: 'Schedule template soft-trashed.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'body'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_CREATED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_CREATED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'create',
    version: 1,
    description: 'Workforce communication draft created.',
    recommendedMetadataFields: ['moduleId', 'communicationType', 'priority'],
    disallowedMetadataFields: ['title', 'body', 'summary', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_UPDATED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'update',
    version: 1,
    description: 'Workforce communication draft updated.',
    recommendedMetadataFields: ['moduleId', 'status'],
    disallowedMetadataFields: ['title', 'body', 'summary', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_SCHEDULED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_SCHEDULED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'schedule',
    version: 1,
    description: 'Workforce communication scheduled for publish.',
    recommendedMetadataFields: ['moduleId', 'scheduledAt'],
    disallowedMetadataFields: ['title', 'body', 'summary', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_PUBLISHED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_PUBLISHED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'publish',
    version: 1,
    description: 'Workforce communication published.',
    recommendedMetadataFields: [
      'moduleId',
      'communicationType',
      'audienceType',
      'recipientCount',
      'requiresAck',
      'priority',
    ],
    disallowedMetadataFields: ['title', 'body', 'summary', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_CANCELLED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_CANCELLED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'cancel',
    version: 1,
    description: 'Workforce communication cancelled.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['title', 'body', 'summary', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_EXPIRED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_EXPIRED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'expire',
    version: 1,
    description: 'Workforce communication expired.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['title', 'body', 'summary', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_TRASHED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'trash',
    version: 1,
    description: 'Workforce communication soft-trashed.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['title', 'body', 'summary', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_RESTORED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'restore',
    version: 1,
    description: 'Workforce communication restored from trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['title', 'body', 'summary', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_COMMUNICATION_PERMANENTLY_DELETED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'purge',
    version: 1,
    description: 'Workforce communication permanently deleted.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['title', 'body', 'summary', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_READ_RECORDED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_READ_RECORDED,
    entityType: 'WorkforceReadReceipt',
    defaultAction: 'read',
    version: 1,
    description: 'Workforce communication read recorded.',
    recommendedMetadataFields: ['moduleId', 'source'],
    disallowedMetadataFields: ['title', 'body', 'email', 'content'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_ACK_COMPLETED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_ACK_COMPLETED,
    entityType: 'WorkforceAcknowledgement',
    defaultAction: 'ack',
    version: 1,
    description: 'Workforce communication acknowledgement completed.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['title', 'body', 'email', 'content', 'ipAddress', 'userAgent'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_CREATED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_CREATED,
    entityType: 'WorkforceCampaign',
    defaultAction: 'create',
    version: 1,
    description: 'Workforce campaign created.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_COMPLETED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_COMPLETED,
    entityType: 'WorkforceCampaign',
    defaultAction: 'complete',
    version: 1,
    description: 'Workforce campaign completed.',
    recommendedMetadataFields: ['moduleId', 'communicationCount'],
    disallowedMetadataFields: ['name', 'description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_TRASHED,
    entityType: 'WorkforceCampaign',
    defaultAction: 'trash',
    version: 1,
    description: 'Workforce campaign soft-trashed.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_RESTORED,
    entityType: 'WorkforceCampaign',
    defaultAction: 'restore',
    version: 1,
    description: 'Workforce campaign restored from trash.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_CAMPAIGN_PERMANENTLY_DELETED,
    entityType: 'WorkforceCampaign',
    defaultAction: 'purge',
    version: 1,
    description: 'Workforce campaign permanently deleted.',
    recommendedMetadataFields: ['moduleId'],
    disallowedMetadataFields: ['name', 'description', 'body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.WORKFORCE_BRIDGE_CREATED]: {
    type: DOMAIN_EVENT_TYPES.WORKFORCE_BRIDGE_CREATED,
    entityType: 'WorkforceCommunication',
    defaultAction: 'bridge',
    version: 1,
    description: 'Cross-module bridge created a workforce communication draft.',
    recommendedMetadataFields: ['moduleId', 'sourceModuleId', 'bridgeKind', 'sourceEntityId'],
    disallowedMetadataFields: ['body', 'title'],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_TIER_CREATED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_TIER_CREATED,
    entityType: 'OrganizationalTier',
    defaultAction: 'create',
    version: 1,
    description: 'Organizational tier created.',
    recommendedMetadataFields: ['name'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_TIER_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_TIER_UPDATED,
    entityType: 'OrganizationalTier',
    defaultAction: 'update',
    version: 1,
    description: 'Organizational tier updated.',
    recommendedMetadataFields: ['changedFields'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_TIER_DELETED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_TIER_DELETED,
    entityType: 'OrganizationalTier',
    defaultAction: 'delete',
    version: 1,
    description: 'Organizational tier deleted.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_DEPARTMENT_CREATED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_DEPARTMENT_CREATED,
    entityType: 'Department',
    defaultAction: 'create',
    version: 1,
    description: 'Department created.',
    recommendedMetadataFields: ['name'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_DEPARTMENT_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_DEPARTMENT_UPDATED,
    entityType: 'Department',
    defaultAction: 'update',
    version: 1,
    description: 'Department updated.',
    recommendedMetadataFields: ['changedFields'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_DEPARTMENT_DELETED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_DEPARTMENT_DELETED,
    entityType: 'Department',
    defaultAction: 'delete',
    version: 1,
    description: 'Department deleted.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_POSITION_CREATED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_POSITION_CREATED,
    entityType: 'Position',
    defaultAction: 'create',
    version: 1,
    description: 'Position created.',
    recommendedMetadataFields: ['title'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_POSITION_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_POSITION_UPDATED,
    entityType: 'Position',
    defaultAction: 'update',
    version: 1,
    description: 'Position updated.',
    recommendedMetadataFields: ['changedFields'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_POSITION_DELETED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_POSITION_DELETED,
    entityType: 'Position',
    defaultAction: 'delete',
    version: 1,
    description: 'Position deleted.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_EMPLOYEE_ASSIGNED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_EMPLOYEE_ASSIGNED,
    entityType: 'EmployeePosition',
    defaultAction: 'assign',
    version: 1,
    description: 'Employee assigned to position.',
    recommendedMetadataFields: ['userId', 'positionId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_EMPLOYEE_REMOVED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_EMPLOYEE_REMOVED,
    entityType: 'EmployeePosition',
    defaultAction: 'remove',
    version: 1,
    description: 'Employee removed from position.',
    recommendedMetadataFields: ['userId', 'positionId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_EMPLOYEE_TRANSFERRED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_EMPLOYEE_TRANSFERRED,
    entityType: 'EmployeePosition',
    defaultAction: 'transfer',
    version: 1,
    description: 'Employee transferred between positions.',
    recommendedMetadataFields: ['userId', 'fromPositionId', 'toPositionId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_PERMISSION_SET_CREATED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_PERMISSION_SET_CREATED,
    entityType: 'PermissionSet',
    defaultAction: 'create',
    version: 1,
    description: 'Permission set created.',
    recommendedMetadataFields: ['name'],
    disallowedMetadataFields: ['permissions'],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_PERMISSION_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_PERMISSION_UPDATED,
    entityType: 'PermissionSet',
    defaultAction: 'update',
    version: 1,
    description: 'Permission set updated.',
    recommendedMetadataFields: ['changedFields'],
    disallowedMetadataFields: ['permissions'],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_PERMISSION_SET_DELETED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_PERMISSION_SET_DELETED,
    entityType: 'PermissionSet',
    defaultAction: 'delete',
    version: 1,
    description: 'Permission set deleted.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: ['permissions'],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_PERMISSION_SET_COPIED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_PERMISSION_SET_COPIED,
    entityType: 'PermissionSet',
    defaultAction: 'copy',
    version: 1,
    description: 'Permission set copied as template.',
    recommendedMetadataFields: ['sourcePermissionSetId', 'newName'],
    disallowedMetadataFields: ['permissions'],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_STRUCTURE_INITIALIZED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_STRUCTURE_INITIALIZED,
    entityType: 'OrgChart',
    defaultAction: 'initialize',
    version: 1,
    description: 'Default org chart structure initialized.',
    recommendedMetadataFields: ['industry'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_MANAGER_ASSIGNED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_MANAGER_ASSIGNED,
    entityType: 'Position',
    defaultAction: 'assignManager',
    version: 1,
    description: 'Position reporting manager assigned.',
    recommendedMetadataFields: ['reportsToId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ORGCHART_MANAGER_REMOVED]: {
    type: DOMAIN_EVENT_TYPES.ORGCHART_MANAGER_REMOVED,
    entityType: 'Position',
    defaultAction: 'removeManager',
    version: 1,
    description: 'Position reporting manager removed.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_CREATED]: {
    type: DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_CREATED,
    entityType: 'ManagerApprovalHierarchy',
    defaultAction: 'create',
    version: 1,
    description: 'Approval hierarchy entry created.',
    recommendedMetadataFields: ['employeePositionId', 'managerPositionId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_UPDATED,
    entityType: 'ManagerApprovalHierarchy',
    defaultAction: 'update',
    version: 1,
    description: 'Approval hierarchy entry updated.',
    recommendedMetadataFields: ['changedFields'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_DELETED,
    entityType: 'ManagerApprovalHierarchy',
    defaultAction: 'delete',
    version: 1,
    description: 'Approval hierarchy entry deleted.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_ASSIGNED]: {
    type: DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_ASSIGNED,
    entityType: 'ManagerApprovalHierarchy',
    defaultAction: 'assign',
    version: 1,
    description: 'Approval hierarchy bulk-assigned to employee, position, or department.',
    recommendedMetadataFields: ['assignmentTarget', 'entriesCreated', 'entriesUpdated'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_VALIDATED]: {
    type: DOMAIN_EVENT_TYPES.APPROVAL_HIERARCHY_VALIDATED,
    entityType: 'Business',
    defaultAction: 'validate',
    version: 1,
    description: 'Approval hierarchy integrity validated for business.',
    recommendedMetadataFields: ['valid', 'issueCount'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.HR_EMPLOYEE_CREATED]: {
    type: DOMAIN_EVENT_TYPES.HR_EMPLOYEE_CREATED,
    entityType: 'EmployeeHRProfile',
    defaultAction: 'create',
    version: 1,
    description: 'HR employee profile created for business workforce.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId'],
    disallowedMetadataFields: ['name', 'email', 'phone', 'ssn'],
  },
  [DOMAIN_EVENT_TYPES.HR_EMPLOYEE_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.HR_EMPLOYEE_UPDATED,
    entityType: 'EmployeeHRProfile',
    defaultAction: 'update',
    version: 1,
    description: 'HR employee profile updated.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId'],
    disallowedMetadataFields: ['name', 'email', 'phone', 'ssn'],
  },
  [DOMAIN_EVENT_TYPES.HR_EMPLOYEE_TERMINATED]: {
    type: DOMAIN_EVENT_TYPES.HR_EMPLOYEE_TERMINATED,
    entityType: 'EmployeeHRProfile',
    defaultAction: 'terminate',
    version: 1,
    description: 'HR employee employment terminated.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId', 'terminationDate'],
    disallowedMetadataFields: ['name', 'email', 'phone', 'ssn'],
  },
  [DOMAIN_EVENT_TYPES.HR_EMPLOYEE_TRASHED]: {
    type: DOMAIN_EVENT_TYPES.HR_EMPLOYEE_TRASHED,
    entityType: 'EmployeeHRProfile',
    defaultAction: 'trash',
    version: 1,
    description: 'HR employee record soft-trashed.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId', 'reason'],
    disallowedMetadataFields: ['name', 'email', 'phone', 'ssn'],
  },
  [DOMAIN_EVENT_TYPES.HR_EMPLOYEE_RESTORED]: {
    type: DOMAIN_EVENT_TYPES.HR_EMPLOYEE_RESTORED,
    entityType: 'EmployeeHRProfile',
    defaultAction: 'restore',
    version: 1,
    description: 'HR employee record restored from trash.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId'],
    disallowedMetadataFields: ['name', 'email', 'phone', 'ssn'],
  },
  [DOMAIN_EVENT_TYPES.HR_EMPLOYEE_PERMANENTLY_DELETED]: {
    type: DOMAIN_EVENT_TYPES.HR_EMPLOYEE_PERMANENTLY_DELETED,
    entityType: 'EmployeeHRProfile',
    defaultAction: 'permanentlyDelete',
    version: 1,
    description: 'HR employee record permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId'],
    disallowedMetadataFields: ['name', 'email', 'phone', 'ssn'],
  },
  [DOMAIN_EVENT_TYPES.HR_ONBOARDING_CREATED]: {
    type: DOMAIN_EVENT_TYPES.HR_ONBOARDING_CREATED,
    entityType: 'OnboardingJourney',
    defaultAction: 'create',
    version: 1,
    description: 'HR onboarding journey started for employee.',
    recommendedMetadataFields: ['moduleId', 'employeeHrProfileId', 'templateId'],
    disallowedMetadataFields: ['name', 'email', 'body'],
  },
  [DOMAIN_EVENT_TYPES.HR_ONBOARDING_COMPLETED]: {
    type: DOMAIN_EVENT_TYPES.HR_ONBOARDING_COMPLETED,
    entityType: 'OnboardingJourney',
    defaultAction: 'complete',
    version: 1,
    description: 'HR onboarding journey completed.',
    recommendedMetadataFields: ['moduleId', 'employeeHrProfileId'],
    disallowedMetadataFields: ['name', 'email', 'body'],
  },
  [DOMAIN_EVENT_TYPES.HR_PTO_REQUESTED]: {
    type: DOMAIN_EVENT_TYPES.HR_PTO_REQUESTED,
    entityType: 'TimeOffRequest',
    defaultAction: 'request',
    version: 1,
    description: 'HR time-off request submitted.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId', 'type'],
    disallowedMetadataFields: ['name', 'email', 'reason'],
  },
  [DOMAIN_EVENT_TYPES.HR_PTO_APPROVED]: {
    type: DOMAIN_EVENT_TYPES.HR_PTO_APPROVED,
    entityType: 'TimeOffRequest',
    defaultAction: 'approve',
    version: 1,
    description: 'HR time-off request approved.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId'],
    disallowedMetadataFields: ['name', 'email', 'reason'],
  },
  [DOMAIN_EVENT_TYPES.HR_PTO_DENIED]: {
    type: DOMAIN_EVENT_TYPES.HR_PTO_DENIED,
    entityType: 'TimeOffRequest',
    defaultAction: 'deny',
    version: 1,
    description: 'HR time-off request denied.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId'],
    disallowedMetadataFields: ['name', 'email', 'reason'],
  },
  [DOMAIN_EVENT_TYPES.HR_ATTENDANCE_EXCEPTION_CREATED]: {
    type: DOMAIN_EVENT_TYPES.HR_ATTENDANCE_EXCEPTION_CREATED,
    entityType: 'AttendanceException',
    defaultAction: 'create',
    version: 1,
    description: 'HR attendance exception recorded.',
    recommendedMetadataFields: ['moduleId', 'employeePositionId', 'type'],
    disallowedMetadataFields: ['name', 'email', 'notes'],
  },
  [DOMAIN_EVENT_TYPES.ENTITLEMENT_SUBSCRIPTION_TIER_CHANGED]: {
    type: DOMAIN_EVENT_TYPES.ENTITLEMENT_SUBSCRIPTION_TIER_CHANGED,
    entityType: 'Subscription',
    defaultAction: 'tier_changed',
    version: 1,
    description: 'Platform subscription tier changed (authoritative entitlement SoR).',
    recommendedMetadataFields: ['previousTier', 'newTier'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ENTITLEMENT_GRANTED]: {
    type: DOMAIN_EVENT_TYPES.ENTITLEMENT_GRANTED,
    entityType: 'Business',
    defaultAction: 'granted',
    version: 1,
    description: 'Entitlement granted to user or business scope.',
    recommendedMetadataFields: ['tier', 'featureKey'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ENTITLEMENT_REVOKED]: {
    type: DOMAIN_EVENT_TYPES.ENTITLEMENT_REVOKED,
    entityType: 'Business',
    defaultAction: 'revoked',
    version: 1,
    description: 'Entitlement revoked from user or business scope.',
    recommendedMetadataFields: ['previousTier', 'featureKey'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.ENTITLEMENT_BUSINESS_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.ENTITLEMENT_BUSINESS_UPDATED,
    entityType: 'Business',
    defaultAction: 'entitlements_updated',
    version: 1,
    description: 'Business derived entitlement cache synced from subscription authority.',
    recommendedMetadataFields: ['tier', 'subscriptionId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.BILLING_SUBSCRIPTION_CREATED]: {
    type: DOMAIN_EVENT_TYPES.BILLING_SUBSCRIPTION_CREATED,
    entityType: 'Subscription',
    defaultAction: 'created',
    version: 1,
    description: 'Platform subscription created via billingService.',
    recommendedMetadataFields: ['tier'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.BILLING_SUBSCRIPTION_UPDATED]: {
    type: DOMAIN_EVENT_TYPES.BILLING_SUBSCRIPTION_UPDATED,
    entityType: 'Subscription',
    defaultAction: 'updated',
    version: 1,
    description: 'Platform subscription updated via billingService.',
    recommendedMetadataFields: ['previousTier', 'newTier', 'changedFields'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.BILLING_SUBSCRIPTION_CANCELLED]: {
    type: DOMAIN_EVENT_TYPES.BILLING_SUBSCRIPTION_CANCELLED,
    entityType: 'Subscription',
    defaultAction: 'cancelled',
    version: 1,
    description: 'Platform subscription cancelled via billingService.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.BILLING_SUBSCRIPTION_RESUMED]: {
    type: DOMAIN_EVENT_TYPES.BILLING_SUBSCRIPTION_RESUMED,
    entityType: 'Subscription',
    defaultAction: 'resumed',
    version: 1,
    description: 'Platform subscription resumed via billingService.',
    recommendedMetadataFields: [],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.BILLING_SYNC_COMPLETED]: {
    type: DOMAIN_EVENT_TYPES.BILLING_SYNC_COMPLETED,
    entityType: 'Subscription',
    defaultAction: 'sync_completed',
    version: 1,
    description: 'Subscription state synced from Stripe via billingService.',
    recommendedMetadataFields: ['source'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.DASHBOARD_TAB_CREATED]: {
    type: DOMAIN_EVENT_TYPES.DASHBOARD_TAB_CREATED,
    entityType: 'Dashboard',
    defaultAction: 'create',
    version: 1,
    description: 'Dashboard tab created.',
    recommendedMetadataFields: ['moduleId', 'contextType', 'userId', 'name'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.DASHBOARD_TAB_DELETED]: {
    type: DOMAIN_EVENT_TYPES.DASHBOARD_TAB_DELETED,
    entityType: 'Dashboard',
    defaultAction: 'delete',
    version: 1,
    description: 'Dashboard tab permanently deleted.',
    recommendedMetadataFields: ['moduleId', 'hardDelete', 'fileAction'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.DASHBOARD_WIDGET_ADDED]: {
    type: DOMAIN_EVENT_TYPES.DASHBOARD_WIDGET_ADDED,
    entityType: 'Widget',
    defaultAction: 'add',
    version: 1,
    description: 'Widget added to dashboard tab.',
    recommendedMetadataFields: ['moduleId', 'widgetType', 'dashboardId'],
    disallowedMetadataFields: [],
  },
  [DOMAIN_EVENT_TYPES.DASHBOARD_WIDGET_REMOVED]: {
    type: DOMAIN_EVENT_TYPES.DASHBOARD_WIDGET_REMOVED,
    entityType: 'Widget',
    defaultAction: 'remove',
    version: 1,
    description: 'Widget removed from dashboard tab.',
    recommendedMetadataFields: ['moduleId', 'widgetType', 'dashboardId'],
    disallowedMetadataFields: [],
  },
};

export function getDomainEventContract(type: string): DomainEventContract | undefined {
  return DOMAIN_EVENT_CONTRACTS[type as DomainEventType];
}

export function isRegisteredDomainEventType(type: string): type is DomainEventType {
  return type in DOMAIN_EVENT_CONTRACTS;
}

/** Strip sensitive / disallowed metadata keys before persistence and fan-out. */
export function sanitizeDomainEventMetadata(
  type: string,
  metadata: Record<string, unknown> | undefined
): Record<string, unknown> {
  if (!metadata) return {};
  const contract = getDomainEventContract(type);
  const disallowed = new Set<string>([
    ...GLOBAL_DISALLOWED_METADATA,
    ...(contract?.disallowedMetadataFields ?? []),
  ]);
  const sanitized: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(metadata)) {
    if (disallowed.has(key)) continue;
    if (val === undefined) continue;
    sanitized[key] = val;
  }
  return sanitized;
}

export type TypedDomainEventInput = Omit<DomainEventEmitInput, 'type' | 'entityType' | 'action'> & {
  entityType?: string;
  action?: string;
  metadata?: Record<string, unknown>;
};

/** Build emit input from registry contract (type-safe at call sites). */
export function buildTypedDomainEventInput(
  eventType: DomainEventType,
  input: TypedDomainEventInput
): DomainEventEmitInput {
  const contract = DOMAIN_EVENT_CONTRACTS[eventType];
  return {
    type: contract.type,
    actorUserId: input.actorUserId,
    dashboardId: input.dashboardId,
    businessId: input.businessId,
    householdId: input.householdId,
    entityType: input.entityType ?? contract.entityType,
    entityId: input.entityId,
    action: input.action ?? contract.defaultAction,
    metadata: sanitizeDomainEventMetadata(contract.type, input.metadata),
  };
}
