/**
 * Canonical Admin Portal control-plane audit taxonomy (Stage 1B-B / AP-F-013).
 * All admin/*Service audit writes must use these constants.
 */

export const ADMIN_AUDIT_ACTIONS = {
  IMPERSONATION_START: 'ADMIN_IMPERSONATION_START',
  IMPERSONATION_END: 'ADMIN_IMPERSONATION_END',
  IMPERSONATION_DENIED: 'ADMIN_IMPERSONATION_DENIED',

  CONTENT_MODERATION_UPDATE: 'ADMIN_CONTENT_MODERATION_UPDATE',
  CONTENT_MODERATION_BULK: 'ADMIN_CONTENT_MODERATION_BULK',

  MODULE_APPROVE: 'ADMIN_MODULE_APPROVE',
  MODULE_REJECT: 'ADMIN_MODULE_REJECT',
  MODULE_STATUS_UPDATE: 'ADMIN_MODULE_STATUS_UPDATE',
  MODULE_VERSION_PROMOTE: 'ADMIN_MODULE_VERSION_PROMOTE',
  MODULE_VERSION_PROMOTE_PREVIOUS: 'ADMIN_MODULE_VERSION_PROMOTE_PREVIOUS',

  SECURITY_EVENT_RESOLVE: 'ADMIN_SECURITY_EVENT_RESOLVE',

  AB_TEST_CREATE: 'ADMIN_AB_TEST_CREATE',
  AB_TEST_UPDATE: 'ADMIN_AB_TEST_UPDATE',
  USER_SEGMENT_CREATE: 'ADMIN_USER_SEGMENT_CREATE',
  CUSTOM_REPORT_GENERATE: 'ADMIN_CUSTOM_REPORT_GENERATE',

  SUPPORT_TICKET_CREATE: 'ADMIN_SUPPORT_TICKET_CREATE',
  SUPPORT_TICKET_UPDATE: 'ADMIN_SUPPORT_TICKET_UPDATE',
  KNOWLEDGE_ARTICLE_CREATE: 'ADMIN_KNOWLEDGE_ARTICLE_CREATE',
  KNOWLEDGE_ARTICLE_UPDATE: 'ADMIN_KNOWLEDGE_ARTICLE_UPDATE',
  LIVE_CHAT_JOIN: 'ADMIN_LIVE_CHAT_JOIN',

  SYSTEM_CONFIG_UPDATE: 'ADMIN_SYSTEM_CONFIG_UPDATE',
  BACKUP_CREATE: 'ADMIN_BACKUP_CREATE',
  MAINTENANCE_MODE_UPDATE: 'ADMIN_MAINTENANCE_MODE_UPDATE',

  OPTIMIZATION_RECOMMENDATION_UPDATE: 'ADMIN_OPTIMIZATION_RECOMMENDATION_UPDATE',
  PERFORMANCE_ALERT_UPDATE: 'ADMIN_PERFORMANCE_ALERT_UPDATE',
  PERFORMANCE_ALERT_CONFIGURE: 'ADMIN_PERFORMANCE_ALERT_CONFIGURE',

  DANGEROUS_MIGRATION_DELETE_DENIED: 'ADMIN_DANGEROUS_MIGRATION_DELETE_DENIED',
  DANGEROUS_MIGRATION_DELETE_EXECUTED: 'ADMIN_DANGEROUS_MIGRATION_DELETE_EXECUTED',
  DANGEROUS_MIGRATION_RESET_DENIED: 'ADMIN_DANGEROUS_MIGRATION_RESET_DENIED',
  DANGEROUS_MIGRATION_RESET_EXECUTED: 'ADMIN_DANGEROUS_MIGRATION_RESET_EXECUTED',
} as const;

export const ADMIN_AUDIT_RESOURCE_TYPES = {
  USER: 'user',
  IMPERSONATION_SESSION: 'impersonation_session',
  CONTENT_REPORT: 'content_report',
  MODULE_SUBMISSION: 'module_submission',
  MODULE: 'module',
  MODULE_VERSION: 'module_version',
  SECURITY_EVENT: 'security_event',
  AB_TEST: 'ab_test',
  USER_SEGMENT: 'user_segment',
  ANALYTICS_REPORT: 'analytics_report',
  SUPPORT_TICKET: 'support_ticket',
  KNOWLEDGE_ARTICLE: 'knowledge_article',
  LIVE_CHAT: 'live_chat',
  SYSTEM_CONFIG: 'system_config',
  BACKUP: 'backup',
  MAINTENANCE: 'maintenance',
  OPTIMIZATION_RECOMMENDATION: 'optimization_recommendation',
  PERFORMANCE_ALERT: 'performance_alert',
  DATABASE_MIGRATION: 'database_migration',
} as const;

export type AdminAuditAction = (typeof ADMIN_AUDIT_ACTIONS)[keyof typeof ADMIN_AUDIT_ACTIONS];
export type AdminAuditResourceType =
  (typeof ADMIN_AUDIT_RESOURCE_TYPES)[keyof typeof ADMIN_AUDIT_RESOURCE_TYPES];

const CANONICAL_ACTIONS = new Set<string>(Object.values(ADMIN_AUDIT_ACTIONS));
const CANONICAL_RESOURCE_TYPES = new Set<string>(Object.values(ADMIN_AUDIT_RESOURCE_TYPES));

export function isCanonicalAdminAuditAction(action: string): action is AdminAuditAction {
  return CANONICAL_ACTIONS.has(action);
}

export function isCanonicalAdminAuditResourceType(
  resourceType: string,
): resourceType is AdminAuditResourceType {
  return CANONICAL_RESOURCE_TYPES.has(resourceType);
}
