/**
 * Phase 7 — Canonical capability taxonomy definitions.
 */
import type { AICapabilityDefinition, AIModelCapability } from 'vssyl-shared';

export const AI_CAPABILITY_DEFINITIONS: Record<AIModelCapability, AICapabilityDefinition> = {
  FAST_CHAT: {
    id: 'FAST_CHAT',
    purpose: 'Low-latency, cost-efficient conversational responses',
    requiredFeatures: ['chat'],
    optionalFeatures: ['streaming'],
    streaming: true,
    vision: false,
    structuredOutput: false,
    toolCalling: false,
    contextWindowHint: '8k–32k typical',
    privacyExpectation: 'standard',
    defaultTier: 'FAST',
    fallbackPolicy: 'FAST → BALANCED_CHAT same privacy class',
  },
  BALANCED_CHAT: {
    id: 'BALANCED_CHAT',
    purpose: 'Default Twin conversational quality with tools',
    requiredFeatures: ['chat', 'streaming'],
    optionalFeatures: ['tool_calls', 'structured_output', 'vision'],
    streaming: true,
    vision: false,
    structuredOutput: true,
    toolCalling: true,
    contextWindowHint: '32k–128k',
    privacyExpectation: 'standard',
    defaultTier: 'BALANCED',
    fallbackPolicy: 'BALANCED → alternate cloud → LOCAL_PRIVATE if sensitive',
  },
  DEEP_REASONING: {
    id: 'DEEP_REASONING',
    purpose: 'High-complexity analysis and multi-hop reasoning',
    requiredFeatures: ['chat'],
    optionalFeatures: ['tool_calls', 'long_context'],
    streaming: true,
    vision: false,
    structuredOutput: true,
    toolCalling: true,
    contextWindowHint: '128k+',
    privacyExpectation: 'standard',
    defaultTier: 'DEEP',
    fallbackPolicy: 'DEEP → BALANCED_CHAT with notice',
  },
  LONG_CONTEXT: {
    id: 'LONG_CONTEXT',
    purpose: 'Large-context synthesis across documents/modules',
    requiredFeatures: ['chat', 'long_context'],
    optionalFeatures: ['structured_output'],
    streaming: true,
    vision: false,
    structuredOutput: true,
    toolCalling: false,
    contextWindowHint: '200k+',
    privacyExpectation: 'standard',
    defaultTier: 'DEEP',
    fallbackPolicy: 'Truncate + BALANCED_CHAT if no long-context model',
  },
  STRUCTURED_EXTRACTION: {
    id: 'STRUCTURED_EXTRACTION',
    purpose: 'Document/fact extraction into structured schemas',
    requiredFeatures: ['structured_output'],
    optionalFeatures: ['vision'],
    streaming: false,
    vision: false,
    structuredOutput: true,
    toolCalling: false,
    contextWindowHint: '32k–128k',
    privacyExpectation: 'elevated',
    defaultTier: 'SPECIALIZED',
    fallbackPolicy: 'Alternate STRUCTURED_EXTRACTION candidate',
  },
  STRUCTURED_SUMMARY: {
    id: 'STRUCTURED_SUMMARY',
    purpose: 'Notebook and page summarization helpers',
    requiredFeatures: ['chat'],
    optionalFeatures: ['structured_output'],
    streaming: false,
    vision: false,
    structuredOutput: true,
    toolCalling: false,
    contextWindowHint: '16k–64k',
    privacyExpectation: 'standard',
    defaultTier: 'FAST',
    fallbackPolicy: 'FAST_CHAT → BALANCED_CHAT',
  },
  VISION: {
    id: 'VISION',
    purpose: 'Image understanding within chat/extraction',
    requiredFeatures: ['vision'],
    optionalFeatures: ['chat', 'structured_output'],
    streaming: true,
    vision: true,
    structuredOutput: true,
    toolCalling: false,
    contextWindowHint: 'provider vision limits',
    privacyExpectation: 'elevated',
    defaultTier: 'SPECIALIZED',
    fallbackPolicy: 'Strip vision → text summaries (existing path)',
  },
  IMAGE_GENERATION: {
    id: 'IMAGE_GENERATION',
    purpose: 'Generate images from prompts',
    requiredFeatures: ['image_generation'],
    optionalFeatures: [],
    streaming: false,
    vision: false,
    structuredOutput: false,
    toolCalling: false,
    contextWindowHint: 'n/a',
    privacyExpectation: 'standard',
    defaultTier: 'SPECIALIZED',
    fallbackPolicy: 'None (modality specific)',
  },
  IMAGE_EDIT: {
    id: 'IMAGE_EDIT',
    purpose: 'Edit existing images',
    requiredFeatures: ['image_edit'],
    optionalFeatures: [],
    streaming: false,
    vision: true,
    structuredOutput: false,
    toolCalling: false,
    contextWindowHint: 'n/a',
    privacyExpectation: 'standard',
    defaultTier: 'SPECIALIZED',
    fallbackPolicy: 'None (modality specific)',
  },
  AUDIO_TRANSCRIPTION: {
    id: 'AUDIO_TRANSCRIPTION',
    purpose: 'Speech-to-text transcription',
    requiredFeatures: ['audio_transcription'],
    optionalFeatures: [],
    streaming: false,
    vision: false,
    structuredOutput: false,
    toolCalling: false,
    contextWindowHint: 'n/a',
    privacyExpectation: 'elevated',
    defaultTier: 'SPECIALIZED',
    fallbackPolicy: 'None (modality specific)',
  },
  TEXT_TO_SPEECH: {
    id: 'TEXT_TO_SPEECH',
    purpose: 'Synthesize speech from text',
    requiredFeatures: ['tts'],
    optionalFeatures: [],
    streaming: false,
    vision: false,
    structuredOutput: false,
    toolCalling: false,
    contextWindowHint: 'n/a',
    privacyExpectation: 'standard',
    defaultTier: 'SPECIALIZED',
    fallbackPolicy: 'None (modality specific)',
  },
  EMBEDDINGS: {
    id: 'EMBEDDINGS',
    purpose: 'Vector embeddings for retrieval',
    requiredFeatures: ['embeddings'],
    optionalFeatures: [],
    streaming: false,
    vision: false,
    structuredOutput: false,
    toolCalling: false,
    contextWindowHint: 'n/a',
    privacyExpectation: 'standard',
    defaultTier: 'SPECIALIZED',
    fallbackPolicy: 'Alternate embeddings model if available',
  },
  LOCAL_PRIVATE: {
    id: 'LOCAL_PRIVATE',
    purpose: 'On-device / no-external processing for sensitive content',
    requiredFeatures: ['local'],
    optionalFeatures: ['chat'],
    streaming: false,
    vision: false,
    structuredOutput: false,
    toolCalling: false,
    contextWindowHint: 'local model limited',
    privacyExpectation: 'local_required',
    defaultTier: 'LOCAL_OR_PRIVATE',
    fallbackPolicy: 'Refuse or human if local insufficient',
  },
};

export function getCapabilityDefinition(id: AIModelCapability): AICapabilityDefinition {
  return AI_CAPABILITY_DEFINITIONS[id];
}
