# Simple Cloud Build for Vssyl Server
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vssyl-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vssyl-server:latest'
      - '-f'
      - './server/Dockerfile.simple'
      - '.'
    id: 'build-server'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vssyl-server:$COMMIT_SHA'
    id: 'push-server'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vssyl-server:latest'
    id: 'push-server-latest'

images:
  - 'gcr.io/$PROJECT_ID/vssyl-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vssyl-server:latest'
