# Optimized Cloud Build with aggressive caching for 3-5 minute builds
steps:
  # Step 1: Restore dependency cache from Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔍 Checking for cached dependencies..."
        
        # Create cache directories
        mkdir -p /workspace/.cache/node_modules
        mkdir -p /workspace/.cache/pnpm
        
        # Try to restore pnpm cache
        gsutil -m cp -r gs://${PROJECT_ID}-build-cache/pnpm-cache/* /workspace/.cache/pnpm/ 2>/dev/null || echo "No pnpm cache found"
        
        # Try to restore node_modules
        gsutil -m cp -r gs://${PROJECT_ID}-build-cache/node_modules/* /workspace/.cache/node_modules/ 2>/dev/null || echo "No node_modules cache found"
        
        echo "✅ Cache restoration attempted"
    id: 'restore-cache'

  # Step 2: Install dependencies with caching
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "📦 Installing dependencies with caching..."
        
        # Install pnpm
        npm install -g pnpm
        
        # Set pnpm cache directory
        export PNPM_HOME="/workspace/.cache/pnpm"
        export PATH="$PNPM_HOME:$PATH"
        
        # Restore node_modules if cached
        if [ -d "/workspace/.cache/node_modules" ]; then
          echo "🚀 Restoring node_modules from cache..."
          cp -r /workspace/.cache/node_modules/* /workspace/ 2>/dev/null || true
        fi
        
        # Install dependencies (will be fast if cache exists)
        pnpm install --frozen-lockfile --prefer-offline --store-dir /workspace/.cache/pnpm
        
        # Build shared package
        echo "🔨 Building shared package..."
        cd shared && pnpm build
        
        echo "✅ Dependencies installed and shared built"
    id: 'install-deps'
    waitFor: ['restore-cache']

  # Step 3: Build server and web in parallel with Docker caching
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vssyl-server:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vssyl-server:latest'
      - '-f'
      - './server/Dockerfile.production'
      - '--build-arg'
      - 'NODE_ENV=production'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/vssyl-server:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    id: 'build-server'
    waitFor: ['install-deps']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vssyl-web:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vssyl-web:latest'
      - '-f'
      - './web/Dockerfile.production'
      - '--build-arg'
      - 'NODE_ENV=production'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/vssyl-web:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    id: 'build-web'
    waitFor: ['install-deps']

  # Step 4: Save cache to Cloud Storage (parallel with push)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "💾 Saving cache for next build..."
        
        # Save pnpm cache
        if [ -d "/workspace/.cache/pnpm" ]; then
          gsutil -m cp -r /workspace/.cache/pnpm/* gs://${PROJECT_ID}-build-cache/pnpm-cache/ 2>/dev/null || true
        fi
        
        # Save node_modules
        if [ -d "/workspace/node_modules" ]; then
          gsutil -m cp -r /workspace/node_modules gs://${PROJECT_ID}-build-cache/node_modules/ 2>/dev/null || true
        fi
        
        echo "✅ Cache saved for next build"
    id: 'save-cache'
    waitFor: ['install-deps']

  # Step 5: Push images in parallel
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vssyl-server:$BUILD_ID']
    id: 'push-server'
    waitFor: ['build-server']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vssyl-server:latest']
    id: 'push-server-latest'
    waitFor: ['build-server']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vssyl-web:$BUILD_ID']
    id: 'push-web'
    waitFor: ['build-web']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vssyl-web:latest']
    id: 'push-web-latest'
    waitFor: ['build-web']

  # Step 6: Deploy services in parallel
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vssyl-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vssyl-server:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--add-cloudsql-instances'
      - 'vssyl-472202:us-central1:vssyl-db'
      - '--vpc-egress'
      - 'all-traffic'
      - '--network'
      - 'default'
      - '--subnet'
      - 'default'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATABASE_URL=postgresql://vssyl_user:Arthur%26George116%21%21@172.30.0.4:5432/vssyl_production?connection_limit=20&pool_timeout=20,DIRECT_URL=postgresql://vssyl_user:Arthur%26George116%21%21@172.30.0.4:5432/vssyl_production?connection_limit=20&pool_timeout=20,JWT_SECRET=OhTXx5RiJu1YOzqGta56ZnN9tTap29sVlvOQMUnGGiI=,JWT_REFRESH_SECRET=/NkIB2sn75WZyqsWOmevzv1wgn9zHuFgmi9x8DTmVG4=,FRONTEND_URL=https://vssyl.com,NEXT_PUBLIC_APP_URL=https://vssyl.com'
    id: 'deploy-server'
    waitFor: ['push-server', 'push-server-latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vssyl-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vssyl-web:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '20'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXTAUTH_URL=https://vssyl.com,NEXTAUTH_SECRET=OhTXx5RiJu1YOzqGta56ZnN9tTap29sVlvOQMUnGGiI=,NEXT_PUBLIC_API_URL=https://vssyl.com/api,NEXT_PUBLIC_API_BASE_URL=https://vssyl.com/api,NEXT_PUBLIC_APP_URL=https://vssyl.com,BACKEND_URL=https://vssyl-server-zykigsc2xa-uc.a.run.app'
    id: 'deploy-web'
    waitFor: ['push-web', 'push-web-latest']

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/vssyl-server:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/vssyl-server:latest'
  - 'gcr.io/$PROJECT_ID/vssyl-web:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/vssyl-web:latest'

# Build options for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Longer timeout for first build, but subsequent builds will be much faster
timeout: '1200s'
