/**
 * Named policy actions. Unimplemented actions fail closed in the policy engine (POLICY_NOT_IMPLEMENTED).
 */
export const POLICY_ACTIONS = {
  DASHBOARD_READ: 'dashboard:read',
  BUSINESS_UPDATE: 'business:update',
  BUSINESS_MEMBER_MANAGE: 'business:member.manage',
  BUSINESS_MEMBER_INVITE: 'business:member.invite',
  BUSINESS_MEMBER_REMOVE: 'business:member.remove',
  BUSINESS_MEMBER_UPDATE: 'business:member.update',
  BUSINESS_MEMBER_ACCEPT_INVITATION: 'business:member.acceptInvitation',
  BUSINESS_MEMBER_RESEND_INVITE: 'business:member.resendInvite',
  BUSINESS_MEMBER_CANCEL_INVITE: 'business:member.cancelInvite',
  MODULE_INSTALL: 'module:install',
  MODULE_UNINSTALL: 'module:uninstall',
  FILE_READ: 'file:read',
  FILE_UPDATE: 'file:update',
  FILE_DELETE: 'file:delete',
  FOLDER_UPDATE: 'folder:update',
  FOLDER_DELETE: 'folder:delete',
  FOLDER_CREATE: 'folder:create',
  FOLDER_SHARE: 'folder:share',
  FILE_MOVE: 'file:move',
  FILE_UPLOAD: 'file:upload',
  FILE_SHARE: 'file:share',
  CALENDAR_READ: 'calendar:calendar.read',
  CALENDAR_CREATE: 'calendar:calendar.create',
  CALENDAR_UPDATE: 'calendar:calendar.update',
  CALENDAR_DELETE: 'calendar:calendar.delete',
  CALENDAR_EVENT_READ: 'calendar:event.read',
  CALENDAR_EVENT_CREATE: 'calendar:event.create',
  CALENDAR_EVENT_UPDATE: 'calendar:event.update',
  CALENDAR_EVENT_DELETE: 'calendar:event.delete',
  CALENDAR_EVENT_RSVP: 'calendar:event.rsvp',
  CALENDAR_AVAILABILITY_READ: 'calendar:availability.read',
  VLINK_CREATE: 'vlink:create',
  VLINK_READ: 'vlink:read',
  VLINK_UPDATE: 'vlink:update',
  VLINK_ARCHIVE: 'vlink:archive',
  VLINK_DELETE: 'vlink:delete',
  VLINK_MEMBER_INVITE: 'vlink:member:invite',
  VLINK_ENTITY_LINK: 'vlink:entity:link',
  VLINK_ENTITY_UNLINK: 'vlink:entity:unlink',
  VLINK_OWNERSHIP_TRANSFER: 'vlink:ownership:transfer',
  TASK_CREATE: 'task:create',
  TASK_UPDATE: 'task:update',
  TASK_DELETE: 'task:delete',
  TODO_TASK_READ: 'todo:task.read',
  TODO_TASK_CREATE: 'todo:task.create',
  TODO_TASK_UPDATE: 'todo:task.update',
  TODO_TASK_COMPLETE: 'todo:task.complete',
  TODO_TASK_REOPEN: 'todo:task.reopen',
  TODO_TASK_DELETE: 'todo:task.delete',
  TODO_TASK_ASSIGN: 'todo:task.assign',
  TODO_PROJECT_READ: 'todo:project.read',
  NOTE_CREATE: 'note:create',
  NOTE_UPDATE: 'note:update',
  NOTE_DELETE: 'note:delete',
  CHAT_CONVERSATION_READ: 'chat:conversation.read',
  CHAT_CONVERSATION_CREATE: 'chat:conversation.create',
  CHAT_CONVERSATION_TRASH: 'chat:conversation.trash',
  CHAT_CONVERSATION_RESTORE: 'chat:conversation.restore',
  CHAT_CONVERSATION_PERMANENT_DELETE: 'chat:conversation.permanentDelete',
  CHAT_MESSAGE_CREATE: 'chat:message.create',
  CHAT_MESSAGE_READ: 'chat:message.read',
  CHAT_MESSAGE_TRASH: 'chat:message.trash',
  CHAT_MESSAGE_RESTORE: 'chat:message.restore',
  CHAT_MESSAGE_PERMANENT_DELETE: 'chat:message.permanentDelete',
  CHAT_MESSAGE_REACT: 'chat:message.react',
  CHAT_THREAD_CREATE: 'chat:thread.create',
} as const;

export type PolicyAction = (typeof POLICY_ACTIONS)[keyof typeof POLICY_ACTIONS];
